/**
 * V17 — suppliers, finance, operations, notifications, reports, the two daily
 * role flows, and the exception playbooks.
 *
 * Delivery-channel statements below reflect the audited production state:
 * email is live, WhatsApp and SMS are not configured.
 */
import type { Article } from "./types";

export const BACKOFFICE_ARTICLES: Article[] = [
  // ───────────────────────────── SUPPLIERS ─────────────────────────────
  {
    slug: "supplier-cost",
    title: "Suppliers and supplier cost",
    bn: "সাপ্লায়ার ও খরচ",
    category: "suppliers",
    what: "The vendors who actually deliver the service — airlines, hotels, embassies, visa partners, tour operators, transport vendors, insurers and couriers — and what they charge you.",
    why: "Supplier cost is what turns a selling price into profit. Without it the agency knows revenue but not margin.",
    who: ["office_incharge", "accounts_manager", "general_manager", "super_admin"],
    when: "On any booking where an outside party delivers part of the service.",
    prerequisites: ["An existing booking", "The supplier's quoted cost"],
    perms: ["supplier:read"],
    steps: [
      { title: "Check the supplier exists", detail: "Business Partners → Suppliers. Suppliers are grouped by type: airline, hotel, embassy, visa, tour, transport, insurance, courier and other.", route: "/partners/suppliers", perm: "supplier:read" },
      { title: "Create the supplier if it is new", detail: "Adding or editing a supplier requires supplier:manage.", perm: "supplier:manage" },
      { title: "Record the cost on the booking", detail: "Enter what the supplier charges you, separately from what you charge the customer.", perm: "vendorcost:read" },
      { title: "Confirm with the supplier", detail: "Only advance the case once the supplier has actually confirmed." },
      { title: "Let it become a payable", detail: "The supplier cost becomes an accounts payable — money the agency owes.", route: "/finance/ap", perm: "ap:read" },
      { title: "Pay and settle", detail: "Finance records the supplier payment and the payable clears.", perm: "ap:manage" },
    ],
    result: "The booking carries both a selling price and a cost, so profit is real; the supplier appears in payables until paid.",
    problems: [
      { problem: "Profit looks too high.", fix: "Supplier cost was probably never recorded. Check the booking before trusting the margin." },
      { problem: "A supplier says they were not paid.", fix: "Open Finance → AP and the supplier ledger to see what is outstanding." },
      { problem: "You cannot see cost figures.", fix: "Supplier cost is gated by vendorcost:read." },
    ],
    seeResult: "Business Partners → Suppliers, and Finance → AP.",
    openTo: "/partners/suppliers",
    openLabel: "Open Suppliers",
    related: ["finance-overview", "supplier-payment", "supplier-unavailable"],
    keywords: ["supplier", "vendor", "cost", "payable", "ap", "airline", "hotel vendor", "buy price", "purchase"],
  },
  {
    slug: "supplier-payment",
    title: "Pay a supplier and check supplier due",
    bn: "সাপ্লায়ার পেমেন্ট",
    category: "suppliers",
    what: "Settling what the agency owes a vendor, and seeing the outstanding balance per supplier.",
    why: "Suppliers stop serving agencies that do not pay. This is where you find out what is owed before it becomes a problem.",
    who: ["accounts_manager", "general_manager", "super_admin"],
    when: "On the supplier's payment terms, or before a large new booking with them.",
    prerequisites: ["A recorded supplier cost or AP document"],
    perms: ["ap:read"],
    steps: [
      { title: "Open Accounts Payable", detail: "Finance → AP lists what the agency owes.", route: "/finance/ap", perm: "ap:read" },
      { title: "Or open the supplier ledger", detail: "Finance → Supplier Ledger shows one supplier's full history.", route: "/finance/supplier-ledger", perm: "ap:read" },
      { title: "Check the AP document", detail: "Open the payable to see which bookings it covers.", perm: "ap:read" },
      { title: "Record the payment", detail: "Settling a payable requires ap:manage.", perm: "ap:manage" },
      { title: "Confirm it cleared", detail: "The payable balance drops; the supplier ledger shows the settlement." },
    ],
    result: "The supplier's outstanding balance reflects reality and the payment is on the ledger.",
    problems: [
      { problem: "'Where can I see supplier due?'", fix: "Finance → AP for all suppliers, or Finance → Supplier Ledger for one." },
      { problem: "A payment is recorded twice.", fix: "Do not delete it — raise it with Finance so it is reversed with an audit trail." },
    ],
    seeResult: "Finance → AP and Finance → Supplier Ledger.",
    openTo: "/finance/ap",
    openLabel: "Open Payables",
    related: ["supplier-cost", "finance-overview", "record-payment"],
    keywords: ["supplier due", "payable", "ap", "pay supplier", "vendor payment", "owe", "outstanding", "settle"],
  },

  // ────────────────────────────── FINANCE ──────────────────────────────
  {
    slug: "finance-overview",
    title: "How money moves through the ERP",
    bn: "টাকার হিসাব কীভাবে চলে",
    category: "finance",
    what: "The complete money path: supplier cost and selling price on a booking, invoice to the customer, payment in, payable out, and what is left as profit.",
    why: "Most finance questions are really this one question. Understanding the path makes every screen obvious.",
    who: ["accounts_manager", "general_manager", "office_incharge", "super_admin"],
    when: "Before working in any finance screen.",
    prerequisites: [],
    perms: ["financial-report:read"],
    steps: [
      { title: "Customer side — invoice then payment", detail: "Booking → selling price → Invoice → customer pays → the invoice becomes partially paid or paid. Anything unpaid is a receivable (AR)." },
      { title: "Supplier side — cost then payment", detail: "Booking → supplier cost → AP document → the agency pays → the payable settles." },
      { title: "Profit", detail: "Selling price minus supplier cost, less expenses. Recorded revenue is only meaningful once cost is entered." },
      { title: "Agent side", detail: "If the customer is agent-owned, commission is earned on the booking and settled through the agent's wallet." },
      { title: "Accounting", detail: "Postings land in the ledger against the chart of accounts, within an accounting period and fiscal year.", route: "/finance/accounting", perm: "gl:read" },
      { title: "Amounts are stored in poisha", detail: "All money is held in minor units — 100 poisha = 1 BDT. Screens display BDT; APIs use poisha." },
    ],
    result: "You can trace any taka from the customer's hand to the agency's profit.",
    problems: [
      { problem: "Revenue looks right but profit does not.", fix: "Supplier cost is missing on some bookings." },
      { problem: "An amount looks 100× too big.", fix: "You are reading poisha as taka. Divide by 100." },
      { problem: "The period is closed.", fix: "Closed periods block posting. Finance must reopen it — see period controls." },
    ],
    seeResult: "Finance → Dashboard for the position; Finance → Reports for detail.",
    openTo: "/finance/dashboard",
    openLabel: "Open Finance Dashboard",
    related: ["create-invoice", "record-payment", "supplier-payment", "receivables"],
    keywords: ["finance", "money", "profit", "revenue", "cost", "ar", "ap", "accounting", "poisha", "how money works"],
  },
  {
    slug: "create-quotation",
    title: "Create a quotation",
    bn: "কোটেশন তৈরি",
    category: "finance",
    what: "A priced offer sent to the customer before any invoice exists.",
    why: "It puts the price in writing and gives the customer something to approve — without committing the agency to a receivable.",
    who: ["marketing_manager", "office_incharge", "general_manager", "super_admin"],
    when: "The customer wants a price before deciding.",
    prerequisites: ["A customer or lead", "The service and its line items"],
    perms: ["quote:manage"],
    steps: [
      { title: "Open Quotations", detail: "CRM & Sales → Quotations.", route: "/sales/quotations", perm: "quote:read" },
      { title: "Create the quotation", detail: "Add lines, any discount and tax. The system numbers it in the QT- series.", perm: "quote:manage",
        fields: [
          { label: "Service type", required: true, note: "Accepted: visa, air_ticket, hotel, tour, hajj, umrah." },
          { label: "Lines", required: true, note: "At least one priced line." },
          { label: "Discount", note: "A fixed amount or a percentage." },
          { label: "Tax", note: "Optional." },
        ],
      },
      { title: "Send it to the customer", detail: "Quotations can be produced as a PDF for sending." },
      { title: "On acceptance, convert", detail: "A quotation can carry its lines into the conversion that creates the customer and booking.", perm: "crm:convert" },
    ],
    result: "A numbered quotation the customer can accept, ready to become a booking and invoice.",
    problems: [
      { problem: "'Invalid serviceType'.", fix: "Quotations exist only for visa, air_ticket, hotel, tour, hajj and umrah. Transport, Student and Manpower cannot be quoted in this build." },
      { problem: "The customer wants a change.", fix: "Revise the same quotation so the history stays in one place." },
    ],
    seeResult: "CRM & Sales → Quotations.",
    openTo: "/sales/quotations",
    openLabel: "Open Quotations",
    related: ["convert-lead", "create-invoice", "qualify-lead"],
    keywords: ["quotation", "quote", "price", "offer", "proposal", "estimate", "QT"],
    availability: "partial",
    availabilityNote: "Quotations support visa, air_ticket, hotel, tour, hajj and umrah only. Transport, Student Consultancy and Manpower cannot be quoted in this build.",
  },
  {
    slug: "create-invoice",
    title: "Create and issue an invoice",
    bn: "ইনভয়েস তৈরি",
    category: "invoices",
    what: "The formal bill to the customer, numbered in the INV- series, with its own lifecycle from draft to paid.",
    why: "It is the agency's legal claim to be paid and the trigger for the whole receivable process.",
    who: ["accounts_manager", "office_incharge", "general_manager", "super_admin"],
    when: "Once the price is agreed — usually inside the booking wizard, or afterwards from Finance.",
    prerequisites: ["A customer", "Usually a booking", "The agreed selling price"],
    perms: ["invoice:manage"],
    steps: [
      { title: "Open Invoices", detail: "Finance → Invoices.", route: "/finance/invoices", perm: "invoice:amount:read" },
      { title: "Create the invoice", detail: "Add the customer, the booking and the line items. It starts as a draft.", perm: "invoice:manage" },
      { title: "Issue it", detail: "Issuing moves it out of draft and makes it a real receivable.", perm: "invoice:manage" },
      { title: "Approve and send", detail: "Approval and sending are separate recorded actions; sending emails the customer.", perm: "invoice:manage" },
      { title: "Watch the status", detail: "draft → issued → sent / approved / viewed → partially_paid → paid. Unpaid past due shows as overdue; cancelled, void and refunded are terminal." },
      { title: "Produce the PDF", detail: "The invoice PDF carries the company details, traveller and passport information, the amount in words and a QR code for verification.", perm: "invoice:amount:read" },
    ],
    result: "A numbered invoice the customer can pay, visible in receivables until settled.",
    problems: [
      { problem: "The amount is wrong after issuing.", fix: "Do not edit history — cancel or void and raise a correct one, so the audit trail stays honest." },
      { problem: "The customer says they never received it.", fix: "Check the invoice audit for the send event and the notification outbox." },
      { problem: "You can see the invoice but not the amount.", fix: "Amounts need invoice:amount:read." },
    ],
    seeResult: "Finance → Invoices, and the case's financial summary in Booking 360.",
    openTo: "/finance/invoices",
    openLabel: "Open Invoices",
    related: ["record-payment", "receivables", "finance-overview", "payment-overdue"],
    keywords: ["invoice", "bill", "INV", "issue", "raise invoice", "make invoice", "pdf", "qr"],
  },
  {
    slug: "record-payment",
    title: "Record a customer payment",
    bn: "পেমেন্ট এন্ট্রি",
    category: "payments",
    what: "Entering money the customer has actually paid, against an invoice and into a cash or bank account.",
    why: "It is the moment a receivable becomes cash. Recorded late or wrongly, the agency chases customers who have already paid.",
    who: ["accounts_manager", "office_incharge", "general_manager", "super_admin"],
    when: "The moment the money is received.",
    prerequisites: ["Money actually received", "The account it went into", "Usually the invoice it settles"],
    perms: ["payment:record"],
    steps: [
      { title: "Open Payments", detail: "Finance → Payments, or use the payment step inside the booking wizard.", route: "/finance/payments", perm: "payment:amount:read" },
      {
        title: "Record the receipt",
        detail: "Enter the amount and choose the receiving account. Both are mandatory.",
        perm: "payment:record",
        fields: [
          { label: "Amount", bn: "পরিমাণ", required: true, note: "Must be greater than zero. Stored in poisha — 100 poisha = 1 BDT." },
          { label: "Account", bn: "অ্যাকাউন্ট", required: true, note: "The cash or bank account the money went into. The payment is refused without it." },
          { label: "Invoice", note: "Strongly recommended — without it the payment is not matched to any bill." },
          { label: "Customer", note: "Links the receipt to the customer's ledger." },
          { label: "Method", note: "Defaults to cash." },
          { label: "Reference", note: "Cheque number, bKash transaction id or bank reference." },
          { label: "Received at", note: "Defaults to now; set it for a back-dated receipt." },
        ],
      },
      { title: "Check the invoice status moved", detail: "Part payment shows partially_paid; full payment shows paid — this happens automatically." },
      { title: "Give the customer a receipt", detail: "A receipt PDF can be produced for the payment.", perm: "payment:amount:read" },
    ],
    result: "The invoice reflects what is paid and what is due; the account balance rises; the customer ledger is updated.",
    problems: [
      { problem: "'amount must be positive'.", fix: "Zero or a negative number was entered. Refunds are a separate action." },
      { problem: "'accountId required'.", fix: "Choose the cash or bank account that received the money." },
      { problem: "The invoice still shows unpaid.", fix: "The payment was recorded without linking the invoice. Finance must correct the link." },
      { problem: "The customer overpaid.", fix: "Record what was actually received, then handle the excess as a refund." },
    ],
    seeResult: "Finance → Payments, the invoice, and Booking 360's financial summary.",
    openTo: "/finance/payments",
    openLabel: "Open Payments",
    related: ["create-invoice", "receivables", "refund", "finance-overview"],
    keywords: ["payment", "receive money", "record payment", "cash", "bkash", "receipt", "paid", "collect", "deposit"],
  },
  {
    slug: "receivables",
    title: "Receivables — who owes the agency",
    bn: "বকেয়া আদায়",
    category: "payments",
    what: "The outstanding balance of everything invoiced but not yet paid.",
    why: "It is the agency's working capital. Unwatched receivables are the fastest way to run out of cash while looking profitable.",
    who: ["accounts_manager", "general_manager", "super_admin"],
    when: "Daily, and before extending more credit to a customer.",
    prerequisites: ["Issued invoices"],
    perms: ["ar:read"],
    steps: [
      { title: "Open Accounts Receivable", detail: "Finance → AR lists what customers owe.", route: "/finance/ar", perm: "ar:read" },
      { title: "Or the customer ledger", detail: "Finance → Customer Ledger shows one customer's full account.", route: "/finance/customer-ledger", perm: "ar:read" },
      { title: "Work the oldest first", detail: "Overdue invoices are the ones at risk. Chase in age order." },
      { title: "Record what you collect", detail: "Every promise-to-pay conversation should end in a recorded payment or a note.", perm: "payment:record" },
      { title: "Check the finance dashboard", detail: "Outstanding receivables and payables are summarised together.", route: "/finance/dashboard", perm: "financial-report:read" },
    ],
    result: "You know exactly who owes what and how old it is.",
    problems: [
      { problem: "'Where can I see customer payment?'", fix: "Finance → Payments for receipts; Finance → AR or Customer Ledger for what remains." },
      { problem: "A paid invoice still shows outstanding.", fix: "The payment was not linked to the invoice — Finance must relink it." },
    ],
    seeResult: "Finance → AR, Customer Ledger, and the Finance Dashboard.",
    openTo: "/finance/ar",
    openLabel: "Open Receivables",
    related: ["record-payment", "create-invoice", "payment-overdue", "finance-overview"],
    keywords: ["receivable", "ar", "due", "outstanding", "owes", "collection", "credit", "unpaid"],
  },

  // ───────────────────────────── OPERATIONS ─────────────────────────────
  {
    slug: "operations-queue",
    title: "Operations queue vs booking workspace",
    bn: "অপারেশন্স কিউ",
    category: "operations",
    what: "The queue is the list of every live case needing attention. The workspace (Booking 360) is where one case is actually worked.",
    why: "The queue answers 'what should the team do next?'; the workspace answers 'what does this case need?'. Confusing them causes missed work.",
    who: ["*"],
    when: "The queue every morning; the workspace whenever you touch a case.",
    prerequisites: ["Live bookings"],
    perms: ["application:read"],
    steps: [
      { title: "Open Operations", detail: "The overview shows live workload.", route: "/operations", perm: "application:read" },
      { title: "Filter to your work", detail: "Filter by service, stage, assignee or status to get to your queue." },
      { title: "Prioritise by risk", detail: "Cases flagged At Risk, or sitting overdue at a stage, come first." },
      { title: "Assign an owner", detail: "Every case should have a named owner.", perm: "application:assign" },
      { title: "Open the case to work it", detail: "Selecting a case opens Booking 360 — documents, stages, money and timeline." },
      { title: "Use the workflow and calendar views", detail: "Operations → Workflow shows stage distribution; Operations → Calendar shows dated commitments.", route: "/operations/workflow", perm: "application:read" },
    ],
    result: "Work is visible, owned and prioritised instead of living in someone's memory.",
    problems: [
      { problem: "The queue is overwhelming.", fix: "Filter to your service and stage. The queue is agency-wide by default." },
      { problem: "A case has no owner.", fix: "Assign it — unassigned cases are the ones that stall." },
      { problem: "You cannot assign.", fix: "Assignment needs application:assign." },
    ],
    seeResult: "Operations → Overview, Workflow and Calendar.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["booking-360", "advance-stage", "at-risk", "admin-daily-flow"],
    keywords: ["operations", "queue", "workspace", "workload", "assign", "pending", "today", "what to do"],
  },
  {
    slug: "workflow-templates",
    title: "Workflow templates and stages",
    bn: "ওয়ার্কফ্লো টেমপ্লেট",
    category: "operations",
    what: "The stage list each service follows. Nine service workflows run 11 stages each: visa, air ticket, hotel, transport, tour, hajj, umrah, student and manpower.",
    why: "Templates make delivery repeatable — every case of the same type follows the same path, so anyone can pick it up.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "When reviewing how a service is delivered, or changing the process.",
    prerequisites: [],
    perms: ["application:read"],
    steps: [
      { title: "See the templates", detail: "Operations → Workflow shows the configured stages.", route: "/operations/workflow", perm: "application:read" },
      { title: "Understand the copy-on-create rule", detail: "When a booking is created, the template's stages are COPIED onto that case. This is the most important thing to know about templates." },
      { title: "Editing affects future cases only", detail: "Changing a template never rewrites cases already in flight — they keep the stages they were created with." },
      { title: "Some services have more than one template", detail: "Visa, for example, has a China (CVASC) 11-stage template alongside a shorter standard one." },
    ],
    result: "You can explain why two cases of the same service show different stages.",
    problems: [
      { problem: "An old case shows different stages from a new one.", fix: "Expected — the template changed after the old case was created." },
      { problem: "A service shows fewer than 11 stages.", fix: "Some secondary templates (medical, immigration, insurance, corporate) are shorter. The nine main services use 11." },
    ],
    seeResult: "Operations → Workflow.",
    openTo: "/operations/workflow",
    openLabel: "Open Workflow",
    related: ["advance-stage", "operations-queue", "visa-workflow"],
    keywords: ["workflow", "template", "stages", "process", "11 stages", "stage list", "configure"],
  },

  // ─────────────────────────── NOTIFICATIONS ───────────────────────────
  {
    slug: "notifications",
    title: "Notifications and message delivery",
    bn: "নোটিফিকেশন",
    category: "notifications",
    what: "How the ERP tells customers and staff that something happened — a stage moved, an invoice was sent, a payment arrived.",
    why: "Customers judge an agency by whether they are kept informed. Automatic notifications remove that burden from staff.",
    who: ["office_incharge", "accounts_manager", "general_manager", "super_admin"],
    when: "Configured events fire automatically; you check delivery when a customer says they heard nothing.",
    prerequisites: [],
    perms: ["comms:read"],
    steps: [
      { title: "Understand the path", detail: "A business event (stage advanced, invoice sent, payment received) raises a notification, which is queued in the outbox, picked up by the scheduler, and handed to a channel adapter." },
      { title: "Email is LIVE", detail: "Email is configured and sending in production. Invoices, stage updates and payment confirmations go out by email." },
      { title: "WhatsApp is NOT CONFIGURED", detail: "There is no WhatsApp provider configured in production. The screens exist, but nothing is delivered over WhatsApp." },
      { title: "SMS is NOT CONFIGURED", detail: "No SMS provider is configured in production. Nothing is delivered by SMS." },
      { title: "Check the outbox and delivery", detail: "Communications → Reports and the notification centre show what was queued and what was delivered.", route: "/comms", perm: "comms:read" },
      { title: "Send a manual message", detail: "Staff can log or send a message against a customer where a channel is available.", perm: "comms:send" },
    ],
    result: "You can tell whether a customer was actually contacted, and by which channel.",
    problems: [
      { problem: "A customer did not get their WhatsApp/SMS.", fix: "Neither channel is configured. Use email or phone. Do not tell the customer a message was sent." },
      { problem: "An email did not arrive.", fix: "Check the outbox for a failure, then check the customer's email address on their record — see the failed notification guide." },
      { problem: "The customer has no email address.", fix: "Nothing can be delivered. Add one to the customer record." },
    ],
    seeResult: "Communications → Reports, and Operations → Notifications.",
    openTo: "/comms",
    openLabel: "Open Communications",
    related: ["failed-notification", "create-invoice", "advance-stage"],
    keywords: ["notification", "email", "whatsapp", "sms", "message", "outbox", "delivery", "alert", "inform"],
    availability: "partial",
    availabilityNote: "Email delivery is LIVE in production. WhatsApp and SMS are NOT CONFIGURED — no message is delivered over those channels.",
  },

  // ───────────────────────────── REPORTS ─────────────────────────────
  {
    slug: "reports",
    title: "Reports and analytics",
    bn: "রিপোর্ট",
    category: "reports",
    what: "The reporting layer: executive, customer, sales, communications and finance analytics, plus per-service reports.",
    why: "It converts daily transactions into decisions — which service earns, which agent performs, what is owed.",
    who: ["general_manager", "accounts_manager", "marketing_manager", "super_admin"],
    when: "Daily for operations, weekly for sales, monthly for finance.",
    prerequisites: ["Recorded bookings, invoices and payments"],
    perms: ["analytics:read"],
    steps: [
      { title: "Executive overview", detail: "Reports → Executive covers pipeline, revenue forecast, booking conversion and team performance.", route: "/analytics", perm: "analytics:read" },
      { title: "Finance analytics", detail: "Revenue by service, outstanding receivables and payables, collections and profit contribution.", route: "/analytics/finance", perm: "analytics:read" },
      { title: "Customer analytics", detail: "Lifetime value, booking frequency, repeat rate and segmentation.", route: "/analytics/customers", perm: "analytics:read" },
      { title: "Sales and communications", detail: "Pipeline performance and messaging activity.", route: "/analytics/sales", perm: "analytics:read" },
      { title: "Per-service reports", detail: "Each vertical has its own reports — visa, ticketing, hotel, transport, tour, hajj and packages." },
      { title: "Export", detail: "Reports can be exported where you hold analytics:export.", perm: "analytics:export" },
    ],
    result: "Management can see performance without asking staff to compile it by hand.",
    problems: [
      { problem: "A report is empty.", fix: "Either no data matches the filter, or the period has no transactions." },
      { problem: "Profit looks wrong.", fix: "Supplier cost is missing on some bookings — revenue is right but margin is not." },
      { problem: "You cannot export.", fix: "Export needs analytics:export." },
    ],
    seeResult: "Reports & Analytics.",
    openTo: "/analytics",
    openLabel: "Open Reports",
    related: ["finance-overview", "admin-daily-flow"],
    keywords: ["report", "analytics", "dashboard", "executive", "export", "performance", "kpi", "revenue"],
  },

  // ─────────────────────────── DAILY FLOWS ───────────────────────────
  {
    slug: "admin-daily-flow",
    title: "Admin & operations — your day",
    bn: "অ্যাডমিনের দৈনিক কাজ",
    category: "getting-started",
    what: "A repeatable daily routine for administrators and operations staff, from login to end-of-day review.",
    why: "The ERP holds a lot. A fixed daily order means nothing important is discovered a week late.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "Every working day.",
    prerequisites: [],
    perms: ["application:read"],
    steps: [
      { title: "1 · Log in and read the dashboard", detail: "Get the overall position before opening anything.", route: "/", perm: "application:read" },
      { title: "2 · New leads", detail: "Anything unassigned from yesterday gets an owner now.", route: "/crm", perm: "lead:read" },
      { title: "3 · New bookings", detail: "Confirm each new case has a customer, documents and an invoice.", route: "/operations", perm: "application:read" },
      { title: "4 · Operations queue", detail: "Work At Risk and overdue cases first.", route: "/operations", perm: "application:read" },
      { title: "5 · Documents needing attention", detail: "Clear failed scans and unverified documents.", route: "/operations/document-intelligence", perm: "ocr:use" },
      { title: "6 · Pending invoices", detail: "Anything delivered but not invoiced is unbilled work.", route: "/finance/invoices", perm: "invoice:amount:read" },
      { title: "7 · Receivables", detail: "Chase the oldest overdue balances.", route: "/finance/ar", perm: "ar:read" },
      { title: "8 · Payables", detail: "Check what suppliers are owed before it affects service.", route: "/finance/ap", perm: "ap:read" },
      { title: "9 · Communications", detail: "Check nothing failed to reach a customer.", route: "/comms", perm: "comms:read" },
      { title: "10 · End-of-day review", detail: "Scan the executive report and confirm every case moved or has a note explaining why not.", route: "/analytics", perm: "analytics:read" },
    ],
    result: "Nothing sits unnoticed for more than a day.",
    problems: [
      { problem: "The queue never empties.", fix: "Cases are being created faster than they are advanced — check assignment and staffing before blaming the system." },
      { problem: "You cannot open a step.", fix: "Each step names its permission; ask an administrator for the ones your role needs." },
    ],
    seeResult: "Dashboard and Operations reflect the day's progress.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["operations-queue", "receivables", "reports", "getting-started"],
    keywords: ["daily", "routine", "day", "morning", "checklist", "admin", "what to do today", "end of day"],
  },
  {
    slug: "agent-daily-flow",
    title: "Agent — your day in the portal",
    bn: "এজেন্টের দৈনিক কাজ",
    category: "agents",
    what: "The B2B agent's working routine inside the agent portal.",
    why: "Agents work their own book. The portal gives them exactly that and nothing else.",
    who: ["*"],
    when: "Every working day.",
    prerequisites: ["An approved agent account with portal access"],
    perms: [],
    steps: [
      { title: "1 · Sign in to the agent portal", detail: "The agent portal has its own login, separate from staff sign-in." },
      { title: "2 · Read the agent dashboard", detail: "Your bookings, your customers and your financial position." },
      { title: "3 · My customers", detail: "Only customers you own are visible. Open an existing one or add a new customer." },
      { title: "4 · Documents and OCR", detail: "Upload the customer's passport and documents so the case is not held up." },
      { title: "5 · New booking", detail: "Create the booking for the service the customer needs, with traveller details and documents." },
      { title: "6 · Track progress", detail: "Follow the case stage by stage from the portal." },
      { title: "7 · Invoice and payment", detail: "See what is invoiced, what is paid and what is due on your bookings." },
      { title: "8 · Commission and wallet", detail: "Check earned commission and your wallet balance; raise top-up or withdrawal requests for the agency to decide." },
      { title: "9 · Follow up the customer", detail: "Close the loop after completion — repeat business is the point." },
    ],
    result: "The agent can trade end-to-end without agency staff retyping anything.",
    problems: [
      { problem: "A customer is missing from your list.", fix: "Ownership was not assigned to you. Ask the agency to assign it." },
      { problem: "You cannot approve your own wallet top-up.", fix: "Correct — wallet decisions, KYC and approvals are agency-side actions." },
      { problem: "You need an admin-only action.", fix: "Contact the agency. There is no workaround, by design." },
    ],
    seeResult: "The agent portal dashboard.",
    openTo: "/partners/agents",
    openLabel: "Open Agents (staff view)",
    related: ["agent-vs-admin", "assign-agent-ownership", "agent-wallet", "agent-commission"],
    keywords: ["agent", "portal", "agent day", "b2b", "my customers", "agent booking", "agent routine"],
  },

  // ───────────────────────── TROUBLESHOOTING ─────────────────────────
  {
    slug: "duplicate-customer",
    title: "Duplicate customer",
    bn: "ডুপ্লিকেট কাস্টমার",
    category: "troubleshooting",
    what: "The same person exists twice, usually because a search was skipped before creating.",
    why: "It splits bookings, documents and money across two records — so neither shows the truth.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "As soon as it is noticed.",
    prerequisites: [],
    perms: ["customer:update"],
    steps: [
      { title: "Detect", detail: "Search by phone number and passport number — the two values people rarely change." },
      { title: "Decide which record survives", detail: "Keep the one with bookings and payments attached. Never the emptier one." },
      { title: "Stop using the other", detail: "Do not create new work on the duplicate." },
      { title: "Escalate", detail: "There is no self-service merge. A supervisor or administrator must consolidate, because bookings, invoices and payments must move together.", perm: "customer:update" },
      { title: "Record it", detail: "Add a note on the surviving record so the history is explainable." },
    ],
    result: "One record carries the relationship; the duplicate is retired.",
    problems: [
      { problem: "Both records have payments.", fix: "Do not attempt this yourself — Finance must move the money with an audit trail." },
      { problem: "You cannot delete the duplicate.", fix: "Deletion needs customer:delete and is deliberately restricted." },
    ],
    seeResult: "Customers — one record with complete history.",
    openTo: "/customers",
    openLabel: "Open Customers",
    related: ["create-customer", "customer-360", "duplicate-passport"],
    keywords: ["duplicate", "double", "same customer", "twice", "merge", "two records"],
  },
  {
    slug: "duplicate-passport",
    title: "Duplicate passport",
    bn: "ডুপ্লিকেট পাসপোর্ট",
    category: "troubleshooting",
    what: "A passport number already recorded against a different customer.",
    why: "A passport belongs to exactly one person. A duplicate means either a data-entry error or the same customer entered twice.",
    who: ["visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "At OCR time — the system can check before you apply.",
    prerequisites: [],
    perms: ["ocr:use"],
    steps: [
      { title: "Detect", detail: "Run the duplicate check during scanning; it compares passport, NID and visa numbers.", perm: "ocr:use" },
      { title: "Stop before applying", detail: "Do not apply the scan to a new customer until the conflict is resolved.", perm: "ocr:apply" },
      { title: "Compare the two customers", detail: "Same name and date of birth means it is one person entered twice." },
      { title: "Same person → treat as duplicate customer", detail: "Follow the duplicate customer guide; keep the record holding the history." },
      { title: "Different people → check for a typo", detail: "One digit misread is the usual cause. Re-scan and correct." },
      { title: "Record the outcome", detail: "Add a note explaining what was decided." },
    ],
    result: "One passport, one customer, and a note explaining the resolution.",
    problems: [
      { problem: "Both records have live cases.", fix: "Escalate to a supervisor — do not move a passport between customers with active visa work." },
    ],
    seeResult: "The customer's passport tab; the Passports list agency-wide.",
    openTo: "/passports",
    openLabel: "Open Passports",
    related: ["scan-passport", "duplicate-customer", "ocr-mismatch"],
    keywords: ["duplicate passport", "already exists", "same passport", "conflict", "passport number"],
  },
  {
    slug: "ocr-mismatch",
    title: "OCR mismatch or missing document",
    bn: "OCR ভুল / ডকুমেন্ট নেই",
    category: "troubleshooting",
    what: "The scan produced wrong or empty values, or a required document was never provided.",
    why: "Bad data reaches an embassy or an airline and costs the customer money and time.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "super_admin"],
    when: "Immediately at review — never after submission.",
    prerequisites: [],
    perms: ["ocr:use"],
    steps: [
      { title: "Detect", detail: "Compare every extracted field against the document in your hand. Failed scans also appear in the Document Intelligence failed list.", route: "/operations/document-intelligence", perm: "ocr:use" },
      { title: "Fix the input, not just the output", detail: "Re-scan flat, well lit, with the whole page and both MRZ lines visible." },
      { title: "Correct manually if it still fails", detail: "Type the correct values and apply. You are accountable for what you apply.", perm: "ocr:apply" },
      { title: "Missing document — hold the case", detail: "Leave the case at its Documents stage and record what is outstanding on the checklist.", perm: "application:update" },
      { title: "Tell the customer what is needed", detail: "Ask for the specific missing document rather than a general chase.", perm: "comms:send" },
      { title: "Verify before moving on", detail: "Mark the document verified only once it is genuinely correct.", perm: "document:verify" },
    ],
    result: "The stored data matches the document, and the case only advances when the file is complete.",
    problems: [
      { problem: "OCR keeps failing on one document.", fix: "It is an image-quality problem. Ask for a fresh scan; do not guess the values." },
      { problem: "You already applied wrong data.", fix: "Correct the customer record and add a note. If the file was submitted, tell a supervisor immediately." },
    ],
    seeResult: "Operations → Document Intelligence.",
    openTo: "/operations/document-intelligence",
    openLabel: "Open Document Intelligence",
    related: ["scan-passport", "verify-document", "duplicate-passport"],
    keywords: ["ocr wrong", "mismatch", "missing document", "failed scan", "blank", "incorrect", "typo", "re-scan"],
  },
  {
    slug: "expired-passport",
    title: "Expired or short-validity passport",
    bn: "পাসপোর্টের মেয়াদ",
    category: "troubleshooting",
    what: "The passport has expired, or does not have enough validity left for the destination.",
    why: "Most countries require six months' validity beyond travel. Submitting anyway wastes the customer's fee.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "super_admin"],
    when: "At OCR review, before any submission or ticketing.",
    prerequisites: [],
    perms: ["ocr:use"],
    steps: [
      { title: "Detect", detail: "The expiry date is extracted by OCR — check it against the travel date, not today's date." },
      { title: "Apply the six-month rule", detail: "If validity beyond travel is under six months, treat it as unusable until you have confirmed the destination's actual rule." },
      { title: "Stop the case", detail: "Hold at Documents. Do not submit to an embassy or issue a ticket.", perm: "application:update" },
      { title: "Tell the customer to renew", detail: "Explain the specific requirement and the deadline.", perm: "comms:send" },
      { title: "Re-scan the new passport", detail: "Scan and apply the renewed passport, then continue.", perm: "ocr:apply" },
    ],
    result: "The case proceeds on a valid passport instead of being rejected downstream.",
    problems: [
      { problem: "Travel is too soon for renewal.", fix: "Escalate — the trip may need rescheduling. Do not submit on an invalid passport." },
      { problem: "The customer insists on proceeding.", fix: "Record the instruction as a note and escalate to a supervisor before acting." },
    ],
    seeResult: "The customer's passport record shows the expiry date.",
    openTo: "/passports",
    openLabel: "Open Passports",
    related: ["scan-passport", "visa-workflow", "ocr-mismatch"],
    keywords: ["expired", "expiry", "passport validity", "six months", "renew", "short validity"],
  },
  {
    slug: "payment-overdue",
    title: "Partial payment and overdue balance",
    bn: "আংশিক পেমেন্ট ও বকেয়া",
    category: "troubleshooting",
    what: "The customer has paid some but not all of an invoice, or the due date has passed.",
    why: "Partial payment is normal in travel. Unmanaged partial payment is how agencies deliver services they never get paid for.",
    who: ["accounts_manager", "office_incharge", "general_manager", "super_admin"],
    when: "At every stage that costs the agency money.",
    prerequisites: [],
    perms: ["ar:read"],
    steps: [
      { title: "Detect", detail: "The invoice shows partially_paid, or appears as overdue in receivables.", route: "/finance/ar", perm: "ar:read" },
      { title: "Check before you spend", detail: "Before issuing a ticket or paying a supplier, confirm what has actually been received." },
      { title: "Record every receipt", detail: "Each instalment is a separate payment against the same invoice.", perm: "payment:record" },
      { title: "Chase in age order", detail: "Oldest first — the most likely to go bad." },
      { title: "Escalate a genuine default", detail: "Hold delivery and escalate rather than quietly absorbing the loss." },
    ],
    result: "The invoice reflects exactly what is paid and what remains, and the agency does not deliver unpaid work by accident.",
    problems: [
      { problem: "The customer says they paid.", fix: "Ask for the reference and check Payments — it may have been recorded without linking the invoice." },
      { problem: "The invoice is not moving to paid.", fix: "The total received is still below the invoice total; check for a short payment." },
    ],
    seeResult: "Finance → AR and the invoice itself.",
    openTo: "/finance/ar",
    openLabel: "Open Receivables",
    related: ["record-payment", "receivables", "create-invoice", "refund"],
    keywords: ["partial", "overdue", "unpaid", "due", "balance", "instalment", "default", "chase"],
  },
  {
    slug: "refund",
    title: "Refund a customer",
    bn: "রিফান্ড",
    category: "troubleshooting",
    what: "Returning money to a customer after cancellation, overpayment or a service that could not be delivered.",
    why: "Refunds are money leaving the agency. They are a separate, more tightly held permission than recording a receipt.",
    who: ["accounts_manager", "general_manager", "super_admin"],
    when: "After cancellation terms and supplier charges are confirmed.",
    prerequisites: ["An existing payment", "Confirmed supplier cancellation charges", "Management approval"],
    perms: ["payment:refund"],
    steps: [
      { title: "Confirm what is actually refundable", detail: "Check the supplier's cancellation charge first — the customer rarely gets back the full amount." },
      { title: "Get approval", detail: "Refunds need payment:refund, held only by Accounts, GM and Super Admin." },
      { title: "Record the refund", detail: "Recorded against the original invoice so the trail is complete.", perm: "payment:refund" },
      { title: "Mark the invoice if fully reversed", detail: "An invoice can be marked refunded where the whole amount is returned.", perm: "payment:refund" },
      { title: "Tell the customer", detail: "Explain the amount and what was deducted.", perm: "comms:send" },
    ],
    result: "Money returned, the invoice reflects it, and the audit trail explains the deduction.",
    problems: [
      { problem: "You do not have the option.", fix: "Refunds require payment:refund — escalate to Accounts." },
      { problem: "The supplier will not refund.", fix: "The agency cannot refund what it cannot recover. Escalate before promising the customer anything." },
    ],
    seeResult: "Finance → Payments shows the refund; the invoice shows the reversal.",
    openTo: "/finance/payments",
    openLabel: "Open Payments",
    related: ["record-payment", "booking-cancelled", "payment-overdue"],
    keywords: ["refund", "return money", "cancel payment", "reverse", "money back", "reimburse"],
  },
  {
    slug: "visa-rejected",
    title: "Visa rejected",
    bn: "ভিসা রিজেক্ট",
    category: "troubleshooting",
    what: "The embassy has refused the application.",
    why: "It is a real outcome, not a system error. The case must record it honestly for the customer's future applications.",
    who: ["visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "As soon as the embassy communicates the decision.",
    prerequisites: ["A submitted visa case"],
    perms: ["application:reject"],
    steps: [
      { title: "Record the decision", detail: "Mark the outcome on the case. Rejection is a specific recorded action.", perm: "application:reject" },
      { title: "Capture the reason", detail: "Add the embassy's stated reason as a note — it determines whether reapplying is viable.", perm: "application:note" },
      { title: "Return the passport", detail: "Collection and delivery still matter. The customer's passport must be returned and recorded." },
      { title: "Settle the money", detail: "Embassy fees are usually non-refundable; agency fees depend on policy. Confirm before promising anything.", perm: "payment:refund" },
      { title: "Advise on reapplying", detail: "Some refusals need a waiting period or new evidence.", perm: "comms:send" },
      { title: "Do not delete the case", detail: "The rejection is part of the customer's history and may be legally relevant." },
    ],
    result: "The rejection, its reason and the passport's return are all recorded.",
    problems: [
      { problem: "The customer demands a full refund.", fix: "Check what was actually paid to the embassy. Escalate to management for the agency portion." },
      { problem: "Someone wants the case deleted.", fix: "Do not. Rejections must remain in the history." },
    ],
    seeResult: "The case in Bookings → Visa with its recorded outcome.",
    openTo: "/visa",
    openLabel: "Open Visa",
    related: ["visa-workflow", "refund", "booking-cancelled"],
    keywords: ["rejected", "refused", "denied", "visa reject", "refusal", "declined"],
  },
  {
    slug: "booking-cancelled",
    title: "Cancellation, wrong service or wrong passenger",
    bn: "বুকিং বাতিল / ভুল তথ্য",
    category: "troubleshooting",
    what: "The customer cancels, changes to a different service, or the booking was created against the wrong person.",
    why: "Each of these has money attached. Handled casually, the agency absorbs a supplier charge nobody authorised.",
    who: ["office_incharge", "accounts_manager", "general_manager", "super_admin"],
    when: "The moment the change is requested.",
    prerequisites: ["An existing booking"],
    perms: ["application:update"],
    steps: [
      { title: "Check supplier terms first", detail: "Before agreeing to anything, find out what the supplier will charge.", perm: "supplier:read" },
      { title: "Wrong passenger or wrong customer", detail: "Correct the details on the case if nothing has been issued. If a ticket or visa was issued, escalate — reissue costs money.", perm: "application:update" },
      { title: "Changed service", detail: "Do not repurpose the case. Close it and create the correct one, so each service keeps its own workflow." },
      { title: "Cancellation", detail: "Record the cancellation on the case with a note giving the reason.", perm: "application:note" },
      { title: "Settle the money", detail: "Cancel or void the invoice, or refund what is due after supplier charges.", perm: "invoice:manage" },
      { title: "Tell the customer the net position", detail: "State clearly what was deducted and why.", perm: "comms:send" },
    ],
    result: "The case reflects reality, the money is settled correctly, and the reason is on record.",
    problems: [
      { problem: "The case was already delivered.", fix: "Delivered work is not cancellable. Handle it as a service complaint and escalate." },
      { problem: "You cannot void the invoice.", fix: "Invoice actions need invoice:manage — escalate to Accounts." },
    ],
    seeResult: "The case's timeline and the invoice status.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["refund", "visa-rejected", "create-invoice"],
    keywords: ["cancel", "cancelled", "wrong passenger", "wrong customer", "change service", "amend", "mistake"],
  },
  {
    slug: "supplier-unavailable",
    title: "Supplier unavailable",
    bn: "সাপ্লায়ার পাওয়া যাচ্ছে না",
    category: "troubleshooting",
    what: "The vendor cannot deliver — no seat, no room, no vehicle, or no response.",
    why: "The customer has already been promised something. Silence is what turns a supply problem into a complaint.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "As soon as the supplier declines or goes quiet.",
    prerequisites: [],
    perms: ["supplier:read"],
    steps: [
      { title: "Hold the case", detail: "Do not advance past confirmation on a supplier that has not confirmed.", perm: "application:update" },
      { title: "Find an alternative", detail: "Business Partners → Suppliers, filtered by type.", route: "/partners/suppliers", perm: "supplier:read" },
      { title: "Re-check the cost", detail: "A different supplier usually means a different cost — update it before promising the old price.", perm: "vendorcost:read" },
      { title: "Tell the customer early", detail: "Explain the change before travel, not on the day.", perm: "comms:send" },
      { title: "If nothing is available", detail: "Cancel properly and refund per the terms, rather than leaving the case open." },
    ],
    result: "Either an alternative supplier is confirmed, or the case is cancelled cleanly.",
    problems: [
      { problem: "The alternative costs more.", fix: "Get management approval before absorbing it or re-quoting the customer." },
      { problem: "Money was already paid to the original supplier.", fix: "Finance must recover it — record the position on the case." },
    ],
    seeResult: "The case's supplier and cost, and the supplier's ledger.",
    openTo: "/partners/suppliers",
    openLabel: "Open Suppliers",
    related: ["supplier-cost", "booking-cancelled", "transport-workflow"],
    keywords: ["supplier unavailable", "no seat", "no room", "sold out", "vendor", "alternative", "no response"],
  },
  {
    slug: "failed-notification",
    title: "A message did not reach the customer",
    bn: "মেসেজ পৌঁছায়নি",
    category: "troubleshooting",
    what: "An email or notification was not delivered, or was never sent at all.",
    why: "Staff assume the system told the customer. When it did not, the customer is left uninformed and blames the agency.",
    who: ["office_incharge", "accounts_manager", "general_manager", "super_admin"],
    when: "Whenever a customer says they heard nothing.",
    prerequisites: [],
    perms: ["comms:read"],
    steps: [
      { title: "Check the channel is real", detail: "Email is LIVE. WhatsApp and SMS are NOT CONFIGURED — if you expected either of those, nothing was ever sent.", route: "/comms", perm: "comms:read" },
      { title: "Check the outbox", detail: "Communications → Reports and the notification centre show queued and delivered messages.", perm: "comms:read" },
      { title: "Check the customer's address", detail: "A missing or mistyped email is the most common cause. Fix it on the customer record.", perm: "customer:update" },
      { title: "Resend", detail: "Send again once the address is corrected, or contact the customer directly.", perm: "comms:send" },
      { title: "Log what you did", detail: "Record the manual contact so the next person is not repeating it.", perm: "comms:manage" },
    ],
    result: "The customer is informed and the record shows how.",
    problems: [
      { problem: "You were told a WhatsApp went out.", fix: "It did not — WhatsApp is not configured in production. Use email or phone." },
      { problem: "The outbox shows a failure.", fix: "Correct the address and resend; if it fails repeatedly, escalate to an administrator." },
    ],
    seeResult: "Communications → Reports, and Operations → Notifications.",
    openTo: "/comms",
    openLabel: "Open Communications",
    related: ["notifications", "create-invoice"],
    keywords: ["not received", "failed email", "no message", "delivery failed", "bounce", "outbox", "resend"],
  },
  {
    slug: "at-risk",
    title: "What does 'At Risk' mean?",
    bn: "'At Risk' মানে কী",
    category: "troubleshooting",
    what: "A health indicator on a case warning that something is wrong — an overdue stage, a missing document, or an unpaid balance.",
    why: "It surfaces trouble before the customer complains.",
    who: ["*"],
    when: "Whenever you see the flag in the queue or on Booking 360.",
    prerequisites: [],
    perms: ["application:read"],
    steps: [
      { title: "Open the case", detail: "The health card names the specific reason — do not guess.", route: "/operations", perm: "application:read" },
      { title: "Overdue stage", detail: "The case has sat too long. Advance it, or add a note explaining the delay.", perm: "application:advance-stage" },
      { title: "Missing document", detail: "The checklist shows what is outstanding. Chase the customer.", perm: "document:upload" },
      { title: "Unpaid balance", detail: "Check receivables before delivering anything further.", perm: "ar:read" },
      { title: "Re-check", detail: "Health recalculates once the underlying cause is cleared." },
    ],
    result: "The case returns to healthy, or carries a note explaining why it cannot yet.",
    problems: [
      { problem: "It stays At Risk after you acted.", fix: "More than one cause. Re-read the health card." },
      { problem: "Everything is At Risk.", fix: "A systemic backlog. Escalate — it is a staffing or process problem, not a data problem." },
    ],
    seeResult: "Booking 360's health card and the operations queue.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["booking-360", "operations-queue", "advance-stage"],
    keywords: ["at risk", "health", "warning", "red", "overdue", "risk", "flag", "attention"],
  },
];
