/**
 * V17 — core journey articles: getting started, leads, customers, agent
 * ownership, documents/OCR and bookings.
 *
 * Every route, permission, field rule and stage name below was read out of the
 * running system during the Phase 0 audit. Nothing here is invented; where the
 * build cannot do something, the article says so via `availability`.
 */
import type { Article } from "./types";

export const CORE_ARTICLES: Article[] = [
  // ─────────────────────────── GETTING STARTED ───────────────────────────
  {
    slug: "getting-started",
    title: "Start here — how the ERP is organised",
    bn: "শুরু করুন",
    category: "getting-started",
    what: "A one-page orientation to Shanghai Travels ERP: how the sidebar is grouped and how a customer's journey moves through it.",
    why: "The menu follows how a travel agency actually works — acquire, book, document, operate, settle — instead of listing features alphabetically. Once you know the order, you can find anything.",
    who: ["*"],
    when: "On your first day, or whenever you cannot find a screen.",
    prerequisites: ["A user account created by an administrator", "Your role decides which menus you can see"],
    perms: [],
    steps: [
      {
        title: "Sign in",
        bn: "লগইন",
        detail: "Enter your email and password. If your account was just created you will be asked to change your password before continuing.",
        route: "/login",
      },
      {
        title: "Read the dashboard",
        detail: "The dashboard is the daily starting point — pending work, financial position and recent activity.",
        route: "/",
      },
      {
        title: "Follow the sidebar in order",
        detail: "CRM & Sales (find work) → Bookings (sell it) → Document Intelligence (paperwork) → Operations (deliver it) → Business Partners (agents/suppliers) → Finance (settle it) → Reports.",
      },
      {
        title: "Use the command palette",
        detail: "Press Ctrl+K (or Cmd+K) anywhere to jump straight to a screen by name instead of hunting through menus.",
      },
      {
        title: "Open the ERP Assistant when stuck",
        detail: "The help button at the bottom-right answers 'how do I…' questions and links directly to the right screen.",
        route: "/help",
      },
    ],
    result: "You can navigate confidently and know which module owns which part of the job.",
    problems: [
      { problem: "A menu item is missing.", fix: "Menus are permission-gated. Your role does not include that permission — ask an administrator if you need it." },
      { problem: "You are sent back to the login page.", fix: "Your session expired. Sign in again; unsaved form data is not kept." },
    ],
    seeResult: "The sidebar reflects exactly what your role may open.",
    openTo: "/",
    openLabel: "Open Dashboard",
    related: ["roles-and-permissions", "admin-daily-flow", "create-booking"],
    keywords: ["start", "begin", "orientation", "navigate", "menu", "sidebar", "login", "first day", "new employee"],
  },
  {
    slug: "roles-and-permissions",
    title: "Roles and permissions — who can do what",
    bn: "রোল ও পারমিশন",
    category: "getting-started",
    what: "The ERP has 7 roles and 88 individual permissions. Every screen and every API action is gated by a permission.",
    why: "It keeps money, customer data and approvals in the right hands, and it is why two people see different menus.",
    who: ["*"],
    when: "When an action is refused, or before asking for extra access.",
    prerequisites: [],
    perms: [],
    steps: [
      {
        title: "Know the roles",
        detail: "Super Admin (all 88 permissions), General Manager (64), Office In-charge (43), Accounts Manager (38), Marketing Manager (24), Visa Consultant (20), Visa Executive (13).",
      },
      {
        title: "Understand the naming",
        detail: "Permissions read as area:action — for example customer:create, application:advance-stage, invoice:manage, payment:record, ocr:apply, commission:read.",
      },
      {
        title: "Super Admin bypasses checks",
        detail: "A Super Admin passes every permission check automatically. Everyone else must hold the exact permission.",
      },
      {
        title: "Ask for access properly",
        detail: "Administration → Users. Only a user with user:manage or role:manage can change a role or its permissions.",
        route: "/admin/users",
        perm: "user:manage",
      },
    ],
    result: "You understand why an action is blocked and who can unblock it.",
    problems: [
      { problem: "'You do not have permission' when saving.", fix: "The screen was visible but the API guard refused. Ask an administrator to grant the specific permission named in the message." },
      { problem: "You can see a record but not its amounts.", fix: "Money is separately gated by invoice:amount:read and payment:amount:read." },
    ],
    seeResult: "Administration → Roles and Administration → Permissions list the live definitions.",
    openTo: "/admin/roles",
    openLabel: "Open Roles",
    related: ["getting-started", "agent-vs-admin"],
    keywords: ["role", "permission", "access", "denied", "cannot", "blocked", "rights", "admin", "super admin"],
  },

  // ────────────────────────────── LEADS ──────────────────────────────
  {
    slug: "create-lead",
    title: "Capture a new lead",
    bn: "নতুন লিড তৈরি",
    category: "leads",
    what: "A lead is an enquiry from someone who is not yet a customer — a walk-in, a phone call, a Facebook message or a website form.",
    why: "It records the enquiry so it is followed up instead of forgotten, and it is the first measurable step of the sales pipeline.",
    who: ["marketing_manager", "office_incharge", "general_manager", "super_admin"],
    when: "The moment an enquiry arrives, before any booking work starts.",
    prerequisites: ["The enquirer's name", "A phone number or email so you can follow up"],
    perms: ["lead:manage"],
    steps: [
      {
        title: "Open Leads",
        bn: "লিড খুলুন",
        detail: "CRM & Sales → Leads.",
        route: "/crm",
        perm: "lead:read",
      },
      {
        title: "Add the lead",
        detail: "Create a new lead and fill the capture form. The system assigns a lead number automatically in the LD- series.",
        perm: "lead:manage",
        fields: [
          { label: "Name", bn: "নাম", required: true, note: "The only mandatory field — the lead is rejected without it." },
          { label: "Source", bn: "সোর্স", required: true, note: "Must be one of: web, walkin, phone, whatsapp, facebook, referral. Defaults to walkin." },
          { label: "Phone", bn: "ফোন", note: "Optional in the system, but without it you cannot follow up." },
          { label: "Email", note: "Optional. Needed if you intend to email a quotation." },
          { label: "Service interest", note: "Which service they asked about." },
          { label: "Priority", note: "hot, warm or cold. Defaults to warm." },
          { label: "Assigned to", note: "The executive who owns the follow-up." },
        ],
      },
      {
        title: "Assign an owner",
        detail: "Set 'Assigned to' so one named person is responsible. Unassigned leads are the ones that go cold.",
        perm: "lead:manage",
      },
    ],
    result: "The lead appears in the Leads list with an LD- number, a source, a priority and an owner.",
    problems: [
      { problem: "'Invalid source' error.", fix: "Only web, walkin, phone, whatsapp, facebook and referral are accepted. Pick the closest one." },
      { problem: "Duplicate enquiry from the same person.", fix: "Search Leads by phone first. If they already exist as a customer, skip the lead and book directly." },
    ],
    seeResult: "CRM & Sales → Leads, newest first.",
    openTo: "/crm",
    openLabel: "Open Leads",
    related: ["qualify-lead", "convert-lead", "create-customer"],
    keywords: ["lead", "enquiry", "inquiry", "new lead", "capture", "walk in", "facebook", "source", "prospect"],
  },
  {
    slug: "qualify-lead",
    title: "Follow up and qualify a lead",
    bn: "লিড ফলো-আপ ও কোয়ালিফাই",
    category: "leads",
    what: "Working the lead — calling, messaging, recording what happened, and deciding whether it is real business.",
    why: "Qualification stops you spending booking effort on enquiries that will never pay, and gives management an honest pipeline.",
    who: ["marketing_manager", "office_incharge", "general_manager", "super_admin"],
    when: "Between capturing the lead and converting it.",
    prerequisites: ["An existing lead with an owner"],
    perms: ["lead:manage"],
    steps: [
      { title: "Open the lead", detail: "CRM & Sales → Leads, then select the lead.", route: "/crm", perm: "lead:read" },
      {
        title: "Log every contact",
        detail: "Record activities as you go — call, meeting, email, whatsapp, task or follow_up. These are the accepted activity types.",
        route: "/crm/activities",
        perm: "crm:read",
      },
      {
        title: "Raise an opportunity when it becomes real",
        detail: "An Opportunity carries the deal through qualification → needs_analysis → proposal → negotiation → won/lost. Each stage has a probability weighting used by the forecast.",
        route: "/crm/opportunities",
        perm: "opportunity:read",
      },
      {
        title: "Quote if the customer wants a price",
        detail: "Quotations are raised from CRM & Sales → Quotations and numbered in the QT- series.",
        route: "/sales/quotations",
        perm: "quote:manage",
      },
      {
        title: "Decide the outcome",
        detail: "Qualified → convert. Not qualified → close it with a lost reason so the pipeline stays honest.",
      },
    ],
    result: "The lead is either ready to convert, or closed with a recorded reason.",
    problems: [
      { problem: "The customer keeps asking for a revised price.", fix: "Revise the quotation rather than creating a new lead — the history stays on one record." },
      { problem: "No answer after several attempts.", fix: "Close it with a lost reason. Lost reasons are configured under CRM settings and feed the conversion report." },
    ],
    seeResult: "CRM & Sales → Reports shows lead sources and conversion.",
    openTo: "/crm/opportunities",
    openLabel: "Open Opportunities",
    related: ["create-lead", "convert-lead", "create-quotation"],
    keywords: ["qualify", "follow up", "followup", "opportunity", "pipeline", "lost", "lost reason", "activity", "call"],
  },
  {
    slug: "convert-lead",
    title: "Convert a lead into a customer and booking",
    bn: "লিড কনভার্ট",
    category: "leads",
    what: "Turning a qualified lead into a real Customer record plus the booking that will be delivered.",
    why: "It carries the enquiry's history forward instead of retyping it, and it is the moment the sales pipeline becomes operational work.",
    who: ["marketing_manager", "office_incharge", "general_manager", "super_admin"],
    when: "As soon as the customer agrees to proceed.",
    prerequisites: ["A qualified lead", "An agreed service type", "The customer's name and phone"],
    perms: ["crm:convert"],
    steps: [
      { title: "Open the qualified lead", detail: "CRM & Sales → Leads.", route: "/crm", perm: "lead:read" },
      {
        title: "Check the customer does not already exist",
        detail: "Search Customers by phone or passport number first. Converting a repeat customer into a second record splits their history permanently.",
        route: "/customers",
        perm: "customer:read",
      },
      {
        title: "Convert",
        detail: "Run Convert on the lead. You must choose a service type — the conversion is refused without a valid one.",
        perm: "crm:convert",
        fields: [
          { label: "Service type", required: true, note: "Accepted: visa, air_ticket, hotel, tour, hajj, umrah." },
          { label: "Lead / Opportunity / Quotation", note: "Any of these can be the source; a linked quotation carries its lines forward." },
        ],
      },
      { title: "Open the new Customer 360", detail: "Verify the details that came across, then continue with documents.", route: "/customers", perm: "customer:read" },
    ],
    result: "A Customer exists with a CUS- code, and the booking work can begin.",
    problems: [
      {
        problem: "Your service is Transport, Student or Manpower and conversion refuses it.",
        fix: "Lead conversion currently accepts only visa, air_ticket, hotel, tour, hajj and umrah. For the other three, create the customer directly and start the case from that service's own screen.",
      },
      { problem: "You converted the wrong lead.", fix: "The created customer and booking must be handled by an administrator — there is no self-service undo." },
    ],
    seeResult: "The new record appears under Customers.",
    openTo: "/crm",
    openLabel: "Open Leads",
    related: ["create-customer", "create-booking", "qualify-lead"],
    keywords: ["convert", "conversion", "lead to customer", "make customer", "won"],
    availability: "partial",
    availabilityNote:
      "Conversion is limited to visa, air_ticket, hotel, tour, hajj and umrah. Transport, Student Consultancy and Manpower cannot be reached through lead conversion in this build — start those from their own module.",
  },

  // ──────────────────────────── CUSTOMERS ────────────────────────────
  {
    slug: "create-customer",
    title: "Create a customer",
    bn: "কাস্টমার তৈরি",
    category: "customers",
    what: "The customer record — the person or company every booking, document, invoice and payment hangs from.",
    why: "Everything in the ERP is organised around the customer. Get this right once and the whole history stays together.",
    who: ["office_incharge", "marketing_manager", "visa_consultant", "general_manager", "super_admin"],
    when: "After a lead is qualified, or immediately for a walk-in who is ready to book.",
    prerequisites: ["Full name", "A working phone number"],
    perms: ["customer:create"],
    steps: [
      { title: "Search before you create", detail: "Open Customers and search by phone, name or passport number. Creating a duplicate splits the customer's history and their financial position.", route: "/customers", perm: "customer:read" },
      {
        title: "Add the customer",
        bn: "কাস্টমার যোগ করুন",
        detail: "Fill the form. A CUS- code is generated automatically — you never type it.",
        perm: "customer:create",
        fields: [
          { label: "Full name", bn: "পুরো নাম", required: true, note: "Minimum 2 characters. Use the passport spelling — it must match for visa and ticketing." },
          { label: "Phone", bn: "ফোন", required: true, note: "Minimum 6 characters." },
          { label: "Email", note: "Optional, but validated if given. Required for emailed invoices." },
          { label: "WhatsApp", note: "Optional." },
          { label: "Nationality", bn: "জাতীয়তা" },
          { label: "Gender" },
          { label: "Date of birth", bn: "জন্ম তারিখ" },
          { label: "Address", bn: "ঠিকানা" },
          { label: "Notes" },
        ],
      },
      { title: "Set agent ownership if applicable", detail: "If a B2B agent introduced this customer, assign ownership now so commission is attributed correctly.", perm: "agent:manage" },
      { title: "Open Customer 360", detail: "Continue with passports and documents.", route: "/customers", perm: "customer:read" },
    ],
    result: "A customer with a CUS- code, ready for documents and bookings.",
    problems: [
      { problem: "'Full name is required (min 2 characters)'.", fix: "The name is blank or a single character." },
      { problem: "'A valid phone number is required'.", fix: "The phone must be at least 6 characters." },
      { problem: "'Email is not valid'.", fix: "Either correct the address or clear the field — email is optional." },
      { problem: "You created a duplicate.", fix: "See the duplicate-customer troubleshooting guide; do not merge by hand." },
    ],
    seeResult: "Customers list, and the Customer 360 workspace for the record.",
    openTo: "/customers",
    openLabel: "Open Customers",
    related: ["customer-360", "assign-agent-ownership", "scan-passport", "duplicate-customer"],
    keywords: ["customer", "add customer", "new customer", "create customer", "client", "passenger", "CUS"],
  },
  {
    slug: "customer-360",
    title: "Customer 360 — everything about one customer",
    bn: "কাস্টমার ৩৬০",
    category: "customers",
    what: "The single workspace showing a customer's profile, bookings, money, documents and communication in one place.",
    why: "It answers 'what is going on with this customer?' without opening five modules — the question staff are asked on the phone every day.",
    who: ["*"],
    when: "Before quoting, before taking payment, and whenever the customer calls.",
    prerequisites: ["An existing customer"],
    perms: ["customer:read"],
    steps: [
      { title: "Open Customers", detail: "Business the customer belongs to you or your branch will be listed.", route: "/customers", perm: "customer:read" },
      { title: "Open the customer", detail: "Selecting a row opens the Customer 360 workspace." },
      { title: "Read the tabs in order", detail: "Profile and identity → bookings → financial position → documents → communication history." },
      { title: "Act from here", detail: "Start a booking, add a document or record a payment without losing the customer's context." },
    ],
    result: "A complete picture of the relationship: what they bought, what they owe, what paperwork exists.",
    problems: [
      { problem: "History looks incomplete.", fix: "The customer probably exists twice. Search by phone and passport number to find the other record." },
      { problem: "You cannot see amounts.", fix: "Money needs invoice:amount:read / payment:amount:read." },
    ],
    seeResult: "The workspace itself is the result.",
    openTo: "/customers",
    openLabel: "Open Customers",
    related: ["create-customer", "assign-agent-ownership", "booking-360"],
    keywords: ["customer 360", "360", "profile", "history", "workspace", "where is customer", "customer detail"],
  },

  // ─────────────────────── AGENTS & OWNERSHIP ───────────────────────
  {
    slug: "assign-agent-ownership",
    title: "Assign a customer to an agent (ownership)",
    bn: "এজেন্ট ওনারশিপ",
    category: "agents",
    what: "Marking which B2B agent owns a customer relationship — or leaving the customer as a house customer owned by the agency.",
    why: "Ownership decides who may see the customer in the agent portal and whose commission is calculated on the booking. Getting it wrong misdirects money.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "At customer creation if an agent introduced them, or later when a relationship changes.",
    prerequisites: ["An existing customer", "An approved agent record"],
    perms: ["agent:manage"],
    steps: [
      { title: "Decide house or agent-owned", detail: "No agent = house customer, belonging to the agency. An agent-owned customer is visible to that agent in their portal." },
      { title: "Open the customer", detail: "Customers → open the record.", route: "/customers", perm: "customer:read" },
      { title: "Verify the agent first", detail: "Business Partners → Agents. Check the agent is approved and active before assigning.", route: "/partners/agents", perm: "commission:read" },
      { title: "Assign the primary owner", detail: "Assign ownership to the agent. This sets the primary agent on the customer.", perm: "agent:manage" },
      { title: "Add a co-agent if two parties share the deal", detail: "A secondary agent can be recorded alongside the primary one.", perm: "agent:manage" },
      { title: "Release when the relationship ends", detail: "Releasing ownership returns the customer to house status.", perm: "agent:manage" },
      { title: "Check the ownership history", detail: "Every assignment, secondary change and release is recorded and readable on the customer.", perm: "customer:read" },
    ],
    result: "The customer shows as agent-owned, the agent can see them in the portal, and commission attaches to their bookings.",
    problems: [
      { problem: "The agent cannot see the customer.", fix: "Ownership was not assigned, or it was assigned to a different agent. Check the ownership history." },
      { problem: "Commission went to the wrong agent.", fix: "Ownership was changed after the booking. Fix ownership, then have Finance review the commission on that booking." },
      { problem: "You do not have the option.", fix: "Ownership changes require agent:manage — an Office In-charge, GM or Super Admin." },
    ],
    seeResult: "The customer record shows the owning agent; ownership history lists every change.",
    openTo: "/partners/agents",
    openLabel: "Open Agents",
    related: ["agent-commission", "agent-wallet", "customer-360", "agent-vs-admin"],
    keywords: ["agent", "ownership", "assign agent", "house customer", "co-agent", "secondary agent", "owner", "b2b"],
  },
  {
    slug: "agent-commission",
    title: "Agent commission",
    bn: "এজেন্ট কমিশন",
    category: "agents",
    what: "What the agency owes an agent for business they introduced, calculated from commission rules and agent tiers.",
    why: "It is the agent's income and a real liability for the agency — it must be traceable to a booking.",
    who: ["accounts_manager", "general_manager", "super_admin"],
    when: "After a booking with an owning agent is invoiced.",
    prerequisites: ["An agent-owned customer", "A booking and invoice"],
    perms: ["commission:read"],
    steps: [
      { title: "Check the commission rules", detail: "Finance → Commission Rules holds the rate configuration.", route: "/finance/commission-rules", perm: "commission:read" },
      { title: "Check the agent's tier", detail: "Agent tiers can carry different rates. Open the agent to see its tier and rate.", route: "/partners/agents", perm: "commission:read" },
      { title: "Review earned commission", detail: "Commissions are listed per agent and tie back to the source booking.", perm: "commission:read" },
      { title: "Settle through the wallet", detail: "Paying commission runs through the agent wallet ledger, not an ad-hoc cash payment.", perm: "commission:manage" },
    ],
    result: "Commission is visible per agent and traceable to the booking that earned it.",
    problems: [
      { problem: "No commission on an agent booking.", fix: "Either the customer was not agent-owned at the time, or no commission rule matched the service." },
      { problem: "The amount looks wrong.", fix: "Check the agent's tier and the rule that applied — do not adjust the number by hand." },
    ],
    seeResult: "Business Partners → Agents, and Finance → Commission Rules.",
    openTo: "/finance/commission-rules",
    openLabel: "Open Commission Rules",
    related: ["assign-agent-ownership", "agent-wallet", "finance-overview"],
    keywords: ["commission", "agent commission", "rate", "tier", "earning", "payout"],
  },
  {
    slug: "agent-wallet",
    title: "Agent wallet — top-up and withdrawal",
    bn: "এজেন্ট ওয়ালেট",
    category: "agents",
    what: "A running balance per agent. Top-ups add funds; withdrawals take them out; every movement is a ledger line.",
    why: "It lets agents transact against a balance and gives the agency one auditable place for agent money.",
    who: ["accounts_manager", "general_manager", "super_admin"],
    when: "When an agent deposits funds, or requests a payout.",
    prerequisites: ["An approved agent"],
    perms: ["commission:read"],
    steps: [
      { title: "Open the agent", detail: "Business Partners → Agents → open the agent.", route: "/partners/agents", perm: "commission:read" },
      { title: "Read the wallet ledger", detail: "The ledger lists every movement with its reason — this is the source of truth, not the summary number.", perm: "commission:read" },
      { title: "Record a top-up or withdrawal", detail: "Both are explicit actions and require commission:manage.", perm: "commission:manage" },
      { title: "Decide pending requests", detail: "Top-up and withdrawal requests raised from the agent portal are approved or rejected centrally.", perm: "commission:manage" },
      { title: "Reconcile", detail: "A reconcile view compares the wallet balance against its ledger.", perm: "commission:read" },
    ],
    result: "The agent's balance matches the sum of its ledger, and every movement has a reason.",
    problems: [
      { problem: "Balance does not match the ledger.", fix: "Use the wallet reconcile view before adjusting anything, and involve Finance." },
      { problem: "An agent says a top-up is missing.", fix: "Check pending wallet requests — it may be awaiting a decision." },
    ],
    seeResult: "The agent's wallet ledger.",
    openTo: "/partners/agents",
    openLabel: "Open Agents",
    related: ["agent-commission", "assign-agent-ownership"],
    keywords: ["wallet", "balance", "top up", "topup", "withdraw", "withdrawal", "agent money", "deposit"],
  },
  {
    slug: "agent-vs-admin",
    title: "Agent portal vs admin ERP — who does what",
    bn: "এজেন্ট বনাম অ্যাডমিন",
    category: "agents",
    what: "The difference between what a B2B agent can do in their own portal and what agency staff do in the main ERP.",
    why: "Agents are external. They must be able to trade without seeing other agents' customers or the agency's internal finance.",
    who: ["*"],
    when: "When onboarding an agent, or explaining why an agent cannot do something.",
    prerequisites: [],
    perms: [],
    steps: [
      { title: "Agents work in the agent portal", detail: "A separate sign-in at the agent portal. Agents see their own dashboard, their own customers, their bookings, their documents, their finance and their reports." },
      { title: "Agents see only what they own", detail: "Portal visibility follows customer ownership. An agent never sees house customers or another agent's customers." },
      { title: "Admin staff work in the main ERP", detail: "Staff use the full ERP with role-based permissions across every customer and every booking." },
      { title: "Approvals stay with the agency", detail: "Agent approval, KYC, suspension, commission rules and wallet decisions are agency-side actions requiring agent:manage or commission:manage." },
      { title: "Never hand an agent an admin instruction", detail: "If a task needs a staff permission, the answer to an agent is to contact the agency — not a workaround." },
    ],
    result: "Clear separation: agents transact on their own book; staff run the agency.",
    problems: [
      { problem: "An agent asks to see all customers.", fix: "Not possible by design. Portal scope is limited to customers they own." },
      { problem: "An agent wants to change a commission rate.", fix: "Agency-side only — requires commission:manage." },
    ],
    seeResult: "Business Partners → Agents shows the agency-side view of every agent.",
    openTo: "/partners/agents",
    openLabel: "Open Agents",
    related: ["assign-agent-ownership", "roles-and-permissions", "agent-daily-flow"],
    keywords: ["agent portal", "b2b", "difference", "agent cannot", "agent access", "portal"],
  },

  // ─────────────────────── DOCUMENTS & OCR ───────────────────────
  {
    slug: "upload-document",
    title: "Upload a customer document",
    bn: "ডকুমেন্ট আপলোড",
    category: "documents",
    what: "Attaching a scan or photo — passport, NID, visa, ticket or supporting paper — to a customer or a booking.",
    why: "Visa and ticketing work cannot proceed without legible documents, and the file must live with the record, not in someone's phone.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "As soon as the customer provides the document.",
    prerequisites: ["An existing customer or booking", "A clear scan or photo — maximum 20 MB"],
    perms: ["document:upload"],
    steps: [
      { title: "Open the customer or booking", detail: "Documents attach to the record they belong to.", route: "/customers", perm: "customer:read" },
      {
        title: "Choose the document type",
        detail: "Supported types: passport, national_id (NID), visa, air_ticket, driving_license, birth_certificate, trade_license, bank_statement, photo, other. There is also an auto option that classifies the document for you.",
      },
      { title: "Upload the file", detail: "Upload the scan. Keep the whole document in frame — for passports the two machine-readable lines at the bottom must be visible and sharp.", perm: "document:upload" },
      { title: "Run OCR if it is an identity document", detail: "Continue to the passport scanning guide.", route: "/operations/document-intelligence", perm: "ocr:use" },
    ],
    result: "The document is stored against the record and appears in its document list.",
    problems: [
      { problem: "Upload refused for size.", fix: "The limit is 20 MB. Re-scan at a lower resolution or as JPEG." },
      { problem: "Wrong document type chosen.", fix: "Upload again with the correct type; ask a supervisor to remove the wrong entry." },
      { problem: "Passport fields come back empty.", fix: "Usually a blurred or cropped image — see the OCR mismatch guide." },
    ],
    seeResult: "Operations → Documents, and the document tab on the customer or booking.",
    openTo: "/operations/documents",
    openLabel: "Open Documents",
    related: ["scan-passport", "verify-document", "ocr-mismatch", "duplicate-passport"],
    keywords: ["upload", "document", "attach", "file", "scan", "nid", "passport", "photo", "paper"],
  },
  {
    slug: "scan-passport",
    title: "Scan a passport with OCR",
    bn: "পাসপোর্ট OCR",
    category: "documents",
    what: "Reading a passport automatically instead of typing it — the system extracts the passport number, name, date of birth, nationality, issue date and expiry date.",
    why: "Typing passport numbers by hand is the single biggest source of visa and ticketing errors. OCR reads the machine-readable zone and validates it.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "Before creating any visa, ticketing, hajj, student or manpower case.",
    prerequisites: ["A clear image of the passport photo page", "The two MRZ lines at the bottom must be readable"],
    perms: ["ocr:use"],
    steps: [
      { title: "Open Document Intelligence", detail: "Operations → Document Intelligence is the OCR workspace.", route: "/operations/document-intelligence", perm: "ocr:use" },
      { title: "Scan the passport", detail: "Upload with document type passport (or auto). The scan is queued and processed.", perm: "ocr:use" },
      {
        title: "Review every extracted field",
        detail: "Compare each value against the passport in your hand. OCR is an assistant, not an authority — you are signing off the data.",
        fields: [
          { label: "Passport number", required: true },
          { label: "Full name", required: true, note: "Must match the ticket exactly." },
          { label: "Date of birth", required: true },
          { label: "Nationality" },
          { label: "Issue date" },
          { label: "Expiry date", note: "Check against the travel date — many countries require 6 months validity." },
        ],
      },
      { title: "Correct anything that is wrong", detail: "Edit the field before applying. Never apply values you have not read." },
      { title: "Check for duplicates", detail: "The system can check whether the passport number already exists against another customer.", perm: "ocr:use" },
      { title: "Apply to the customer", detail: "Applying writes the verified fields onto the customer and creates the passport record. This is a separate, stronger permission than scanning.", perm: "ocr:apply" },
    ],
    result: "The customer has a stored passport with verified details, and booking can proceed.",
    problems: [
      { problem: "Fields are blank or wrong.", fix: "Re-scan flat, in good light, with the MRZ lines fully visible. See the OCR mismatch guide." },
      { problem: "The passport is already on another customer.", fix: "Stop — see the duplicate passport guide. Do not create a second customer." },
      { problem: "Apply is not available to you.", fix: "Scanning needs ocr:use; writing to the customer needs ocr:apply." },
      { problem: "The passport expires too soon.", fix: "See the expired passport guide before booking travel." },
    ],
    seeResult: "The customer's passport tab, and Passports for the agency-wide list.",
    openTo: "/operations/document-intelligence",
    openLabel: "Open Document Intelligence",
    related: ["upload-document", "verify-document", "duplicate-passport", "expired-passport", "ocr-mismatch"],
    keywords: ["ocr", "passport", "scan", "mrz", "extract", "read passport", "passport number", "auto fill"],
  },
  {
    slug: "verify-document",
    title: "Verify documents and clear the queue",
    bn: "ডকুমেন্ট যাচাই",
    category: "documents",
    what: "The check that a stored document is genuine, legible and matches the customer — and the queue of scans needing attention.",
    why: "An unverified document that reaches an embassy costs the customer a rejection and the agency its reputation.",
    who: ["visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "After OCR, before the case is submitted anywhere.",
    prerequisites: ["An uploaded document, ideally already scanned"],
    perms: ["document:verify"],
    steps: [
      { title: "Open Document Intelligence", detail: "It shows scan statistics, recent scans and failed scans.", route: "/operations/document-intelligence", perm: "ocr:use" },
      { title: "Work the failed scans", detail: "Failed items are the queue. Each one is a document that could not be read and needs a human." },
      { title: "Compare against the original", detail: "Check name spelling, passport number and dates against the document itself." },
      { title: "Mark as verified", detail: "Verification is a distinct permission — it is a sign-off, not a formality.", perm: "document:verify" },
      { title: "Reprocess in bulk if a batch failed", detail: "Pending scans can be reprocessed together.", perm: "ocr:apply" },
    ],
    result: "Documents are verified and the case can move to submission.",
    problems: [
      { problem: "Repeated failures on one document.", fix: "The image quality is the cause. Ask for a fresh scan." },
      { problem: "You can scan but not verify.", fix: "Verification requires document:verify." },
      { problem: "Passport data is sensitive.", fix: "Reading passport documents is separately gated by document:read-passport; raw OCR text needs ocr:read-raw." },
    ],
    seeResult: "Operations → Document Intelligence, failed and recent lists.",
    openTo: "/operations/document-intelligence",
    openLabel: "Open Document Intelligence",
    related: ["scan-passport", "upload-document", "ocr-mismatch"],
    keywords: ["verify", "verification", "queue", "failed", "check document", "approve document", "review"],
  },

  // ───────────────────────────── BOOKINGS ─────────────────────────────
  {
    slug: "create-booking",
    title: "Create a booking",
    bn: "বুকিং তৈরি",
    category: "bookings",
    what: "The guided path that turns an agreed sale into a tracked case: service → customer → documents → traveller → supplier → invoice → payment.",
    why: "It creates the case, its workflow stages and its invoice together, so nothing is delivered without a financial record.",
    who: ["office_incharge", "visa_consultant", "marketing_manager", "general_manager", "super_admin"],
    when: "Once the customer has agreed and their documents are in hand.",
    prerequisites: ["An existing customer (or their name and phone to create one)", "Verified passport for travel services", "The agreed selling price"],
    perms: ["application:create"],
    steps: [
      { title: "Open New Booking", detail: "Bookings → New booking starts the unified wizard.", route: "/bookings/new", perm: "application:create" },
      { title: "1 · Service", detail: "Choose the service. Visa, Air Ticket, Hotel, Tour, Transport, Hajj and Umrah can be created here. Student Consultancy and Manpower are not selectable in this wizard — start those from their own screens." },
      { title: "2 · Package", detail: "Pick a package where the service uses one (tour, hajj, umrah)." },
      { title: "3 · Customer", detail: "Select an existing customer or create one inline. A new customer needs a name and a phone number — the wizard will not advance without both.", perm: "customer:create" },
      { title: "4 · Documents", detail: "Attach or confirm the documents this service needs.", perm: "document:upload" },
      { title: "5 · Traveller", detail: "Confirm traveller details. The name must match the passport exactly." },
      { title: "6 · Supplier", detail: "Record the supplier and the cost. Full supplier assignment lives on the service desk — capture the note here for operations.", perm: "supplier:read" },
      { title: "7 · Review", detail: "Check service, customer, traveller and price before creating anything." },
      { title: "8 · Invoice", detail: "Raise the invoice for the selling price.", perm: "invoice:manage" },
      { title: "9 · Payment", detail: "Record any money taken now — full, partial or none.", perm: "payment:record" },
      { title: "10 · Done", detail: "The booking gets an APP- reference. Continue in Booking 360." },
    ],
    result: "A booking with an APP- reference, its own workflow stages, an invoice, and a place in the operations queue.",
    problems: [
      { problem: "'Choose a service'.", fix: "Nothing was selected at step 1." },
      { problem: "'Select or create a customer'.", fix: "Step 3 needs an existing customer or a new one." },
      { problem: "'New customer needs name and phone'.", fix: "Both fields are mandatory." },
      { problem: "'This service type is not yet supported.'", fix: "Student and Manpower are blocked in the wizard. Use Students → New or Manpower → New instead." },
    ],
    seeResult: "Bookings list, and the Booking 360 workspace for this case.",
    openTo: "/bookings/new",
    openLabel: "Start a Booking",
    related: ["booking-360", "operations-queue", "create-invoice", "record-payment"],
    keywords: ["booking", "new booking", "create booking", "wizard", "application", "case", "APP", "sell"],
    availability: "partial",
    availabilityNote:
      "The unified wizard covers Visa, Air Ticket, Hotel, Tour, Transport, Hajj and Umrah. Student Consultancy and Manpower must be created from their own module screens — the wizard marks them 'Not yet supported'.",
  },
  {
    slug: "booking-360",
    title: "Booking 360 — working a case",
    bn: "বুকিং ৩৬০",
    category: "bookings",
    what: "The workspace for one booking: summary, customer, agent, service detail, stage progress, money, documents, timeline, audit and quick actions.",
    why: "It is where a case is actually delivered. Everything needed to move it forward is on one screen.",
    who: ["*"],
    when: "Every time you touch a booking after it exists.",
    prerequisites: ["An existing booking"],
    perms: ["application:read"],
    steps: [
      { title: "Open the booking", detail: "From the Bookings list, the operations queue, or the customer's booking tab.", route: "/bookings/new", perm: "application:read" },
      { title: "Read the health indicator", detail: "Health summarises whether the case is on track — overdue stages, missing documents or unpaid balance pull it down." },
      { title: "Check stage progress", detail: "The stage strip shows where the case is in its 11-stage workflow and what comes next." },
      { title: "Check the financial summary", detail: "Invoiced, paid and due for this case.", perm: "invoice:amount:read" },
      { title: "Check documents", detail: "The checklist shows what this service needs and what is still missing." },
      { title: "Read the timeline", detail: "Every stage change, note and event in order — grouped as Today, Yesterday, This Week and Earlier." },
      { title: "Use quick actions", detail: "Advance the stage, add a note, assign an owner or open the invoice without leaving the case.", perm: "application:advance-stage" },
    ],
    result: "You know the exact state of the case and can move it forward.",
    problems: [
      { problem: "Health shows At Risk.", fix: "Something is overdue, missing or unpaid — the card names it. Clear that item." },
      { problem: "You cannot advance the stage.", fix: "Advancing needs application:advance-stage." },
      { problem: "Money is hidden.", fix: "Amounts need invoice:amount:read." },
    ],
    seeResult: "The workspace itself; the timeline records what you did.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["create-booking", "advance-stage", "operations-queue", "at-risk"],
    keywords: ["booking 360", "360", "case", "workspace", "timeline", "health", "stage", "detail", "open booking"],
  },
  {
    slug: "advance-stage",
    title: "Advance a booking to the next stage",
    bn: "স্টেজ এগিয়ে নিন",
    category: "operations",
    what: "Moving a case forward through its workflow — the action that records real progress.",
    why: "The stage is how everyone else knows where the case stands, and it drives notifications and reporting.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "Whenever the real-world step is genuinely complete.",
    prerequisites: ["An existing booking", "The work for the current stage actually finished"],
    perms: ["application:advance-stage"],
    steps: [
      { title: "Open the case", detail: "From the operations queue or Booking 360.", route: "/operations", perm: "application:read" },
      { title: "Confirm the current stage is truly done", detail: "Advancing is recorded against your name in the audit trail." },
      { title: "Advance", detail: "The case moves to the next stage of its template and the timeline records it.", perm: "application:advance-stage" },
      { title: "Add a note when the reason matters", detail: "Notes are how the next person understands what happened.", perm: "application:note" },
      { title: "Let the notification go out", detail: "Configured stage events raise a customer notification automatically." },
    ],
    result: "The case sits at the next stage, the timeline shows who moved it and when.",
    problems: [
      { problem: "You advanced too far by mistake.", fix: "There is no self-service reversal. Add a note explaining it and escalate to a supervisor." },
      { problem: "Stages differ between services.", fix: "Each service has its own 11-stage template — read that service's guide." },
      { problem: "Permission denied.", fix: "Needs application:advance-stage; approvals additionally need application:approve." },
    ],
    seeResult: "The stage strip in Booking 360 and the operations queue.",
    openTo: "/operations",
    openLabel: "Open Operations",
    related: ["booking-360", "operations-queue", "workflow-templates"],
    keywords: ["advance", "next stage", "move stage", "progress", "stage", "workflow", "forward"],
  },
];
