/**
 * V17 — the eight service verticals.
 *
 * Every stage list below is the LIVE WorkflowTemplateStage content read from
 * the production database during the Phase 0 audit — not a paraphrase. If a
 * template is edited later, existing cases keep the stages they were created
 * with; only new cases pick up the change.
 */
import type { Article, Step } from "./types";

/** Renders a real template's stages as a single reference step. */
const stagesStep = (service: string, stages: string[]): Step => ({
  title: `The ${stages.length} stages`,
  detail: `${service}: ${stages.map((s, i) => `${i + 1}. ${s}`).join("  →  ")}`,
});

export const VISA_STAGES = [
  "Created", "Documents", "OCR", "Review", "Embassy Submission", "Interview",
  "Approved", "Stamped", "Collected", "Delivered", "Completed",
];
export const TICKET_STAGES = [
  "Created", "Documents", "Fare Search", "Fare Confirmed", "Payment Pending",
  "Ticket Issued", "PNR Confirmed", "Delivered", "Travel Started", "Travel Completed", "Closed",
];
export const HOTEL_STAGES = [
  "Created", "Documents", "Hotel Search", "Room Reserved", "Payment Pending",
  "Booking Confirmed", "Voucher Issued", "Guest Checked In", "Guest Checked Out", "Completed", "Closed",
];
export const TRANSPORT_STAGES = [
  "Created", "Documents", "Vehicle Assigned", "Driver Assigned", "Payment Pending",
  "Booking Confirmed", "Pickup Ready", "Passenger Picked Up", "Trip Completed", "Delivered", "Closed",
];
export const TOUR_STAGES = [
  "Created", "Documents", "Itinerary Planning", "Quote Confirmed", "Payment Pending",
  "Booking Confirmed", "Pre-departure Briefing", "Travel Started", "Travel Completed", "Feedback", "Closed",
];
export const HAJJ_STAGES = [
  "Created", "Documents", "Package Selected", "Payment Pending", "Visa Processing",
  "Ticketing & Hotel", "Pre-departure Orientation", "Departed", "On-ground Servicing", "Returned", "Closed",
];
export const STUDENT_STAGES = [
  "Created", "Documents", "Counseling", "University Selection", "Application Submitted",
  "Offer Received", "Payment Pending", "Visa Processing", "Pre-departure", "Enrolled", "Closed",
];
export const MANPOWER_STAGES = [
  "Created", "Documents", "Employer Verification", "Medical & Training", "Payment Pending",
  "Visa / Work Permit", "BMET Clearance", "Ticketing", "Deployed", "Post-deployment", "Closed",
];

export const SERVICE_ARTICLES: Article[] = [
  {
    slug: "visa-workflow",
    title: "Visa case — the 11-stage workflow",
    bn: "ভিসা প্রসেস",
    category: "visa",
    what: "The end-to-end visa case, from documents through embassy submission to handing the passport back to the customer.",
    why: "Visa is the agency's core service. The stages exist so an embassy deadline is never missed and every passport is accounted for.",
    who: ["visa_executive", "visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "Whenever a customer needs a visa.",
    prerequisites: ["A customer with a verified, valid passport", "The destination and visa type", "Embassy/CVASC document checklist met"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the visa case", detail: "New Booking → Visa, or Bookings → Visa → New.", route: "/visa", perm: "application:create" },
      stagesStep("Visa (China / CVASC)", VISA_STAGES),
      { title: "Documents (stage 2)", detail: "Collect and upload everything the embassy requires. The checklist on the case tracks what is outstanding.", perm: "document:upload" },
      { title: "OCR (stage 3)", detail: "Scan the passport and apply the verified fields to the customer.", route: "/operations/document-intelligence", perm: "ocr:use" },
      { title: "Review (stage 4)", detail: "A consultant checks the file end-to-end. This is the last chance to catch a spelling or date error cheaply.", perm: "document:verify" },
      { title: "Embassy Submission (stage 5)", detail: "The file goes to the embassy or CVASC centre and the case is marked submitted.", perm: "application:submit-to-embassy" },
      { title: "Interview (stage 6)", detail: "Where the mission requires one. Record the outcome as a note.", perm: "application:note" },
      { title: "Approved (stage 7) / Stamped (stage 8)", detail: "The decision, then the physical visa in the passport." },
      { title: "Collected (stage 9)", detail: "The agency has the passport back from the embassy. The collection date is stamped on the case." },
      { title: "Delivered (stage 10)", detail: "The passport is handed to the customer. The delivery date is stamped — this is the proof it left the office." },
      { title: "Completed (stage 11)", detail: "Case closed. Confirm the invoice is settled." },
    ],
    result: "The customer has their visa, the case is Completed, and collection and delivery are both timestamped.",
    problems: [
      { problem: "The visa is rejected.", fix: "See the visa rejection guide — do not delete the case." },
      { problem: "The passport expires within 6 months.", fix: "See the expired passport guide before submitting." },
      { problem: "The embassy asks for another document.", fix: "Upload it against the case and add a note; leave the stage where it is until the file is resubmitted." },
      { problem: "The name does not match the ticket.", fix: "Correct it before submission — see the OCR mismatch guide." },
    ],
    seeResult: "Bookings → Visa, and the case's Booking 360.",
    openTo: "/visa",
    openLabel: "Open Visa",
    related: ["scan-passport", "advance-stage", "visa-rejected", "expired-passport", "booking-360"],
    keywords: ["visa", "embassy", "cvasc", "china visa", "stamped", "collected", "delivered", "submission", "interview"],
  },
  {
    slug: "ticketing-workflow",
    title: "Air ticket — the 11-stage workflow",
    bn: "এয়ার টিকিট",
    category: "ticketing",
    what: "Flight ticketing from fare search through issue and travel.",
    why: "Fares change and names must match passports exactly — the stages force both to be confirmed before money is spent.",
    who: ["office_incharge", "visa_consultant", "general_manager", "super_admin"],
    when: "Whenever a customer needs a flight.",
    prerequisites: ["Passenger name exactly as printed in the passport", "Travel dates and route", "A supplier or airline to issue through"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the ticketing case", detail: "New Booking → Air Ticket, or Bookings → Ticketing → New.", route: "/ticketing", perm: "application:create" },
      stagesStep("Air Ticket", TICKET_STAGES),
      { title: "Fare Search (stage 3)", detail: "Find options against the requested route and dates." },
      { title: "Fare Confirmed (stage 4)", detail: "The customer accepts a fare. Record the selling price on the case." },
      { title: "Payment Pending (stage 5)", detail: "Most airlines need money before issue. Raise the invoice and record payment.", perm: "payment:record" },
      { title: "Ticket Issued (stage 6) / PNR Confirmed (stage 7)", detail: "The ticket is issued and the PNR recorded on the case." },
      { title: "Delivered (stage 8)", detail: "The e-ticket reaches the customer." },
      { title: "Travel Started (9) → Travel Completed (10) → Closed (11)", detail: "Track the journey to closure so the case does not sit open forever." },
    ],
    result: "An issued ticket with its PNR on the case, paid and delivered.",
    problems: [
      { problem: "The passenger name is misspelled.", fix: "Airlines charge for name corrections. Fix before issue — after issue, contact the airline via the supplier." },
      { problem: "The fare expired before payment.", fix: "Return to Fare Search and re-confirm; do not issue on a stale fare." },
      { problem: "Payment has not arrived but the customer wants the ticket.", fix: "Escalate — issuing unpaid creates a receivable against the agency." },
    ],
    seeResult: "Bookings → Ticketing.",
    openTo: "/ticketing",
    openLabel: "Open Ticketing",
    related: ["create-booking", "record-payment", "supplier-cost", "advance-stage"],
    keywords: ["ticket", "air ticket", "flight", "pnr", "fare", "airline", "issue ticket", "e-ticket"],
  },
  {
    slug: "hotel-workflow",
    title: "Hotel — the 11-stage workflow",
    bn: "হোটেল বুকিং",
    category: "hotel",
    what: "Hotel reservations from search through voucher, stay and completion.",
    why: "A hotel is only real once it is confirmed and a voucher exists — the stages stop a guest arriving to no booking.",
    who: ["office_incharge", "visa_consultant", "general_manager", "super_admin"],
    when: "Whenever a customer needs accommodation.",
    prerequisites: ["City, dates and room requirement", "Guest names", "A hotel supplier"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the hotel case", detail: "New Booking → Hotel, or Bookings → Hotels → New.", route: "/hotels", perm: "application:create" },
      stagesStep("Hotel", HOTEL_STAGES),
      { title: "Hotel Search (3) → Room Reserved (4)", detail: "Find and hold the room. Record the hotel and room type on the case." },
      { title: "Payment Pending (5) → Booking Confirmed (6)", detail: "Collect payment per the supplier's terms, then confirm.", perm: "payment:record" },
      { title: "Voucher Issued (stage 7)", detail: "The voucher is the guest's proof at check-in — deliver it before travel." },
      { title: "Guest Checked In (8) → Checked Out (9) → Completed (10) → Closed (11)", detail: "Track the stay so any dispute has a record." },
    ],
    result: "A confirmed hotel booking with a delivered voucher and a completed stay.",
    problems: [
      { problem: "The hotel cannot confirm.", fix: "Return to Hotel Search and offer an alternative before taking more money." },
      { problem: "The guest name differs from the passport.", fix: "Correct it before the voucher is issued." },
      { problem: "The customer cancels.", fix: "Check the supplier's cancellation terms first — see the cancellation guide." },
    ],
    seeResult: "Bookings → Hotels. Hotel master data lives under Hotels → Catalog.",
    openTo: "/hotels",
    openLabel: "Open Hotels",
    related: ["create-booking", "supplier-cost", "record-payment", "booking-cancelled"],
    keywords: ["hotel", "room", "voucher", "check in", "checkout", "accommodation", "reservation", "stay"],
  },
  {
    slug: "transport-workflow",
    title: "Transport — the 11-stage workflow",
    bn: "ট্রান্সপোর্ট",
    category: "transport",
    what: "Vehicle transfers and trips, from vehicle and driver assignment through to trip completion.",
    why: "A transfer fails if no vehicle or driver is actually assigned — the stages make both explicit.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "Airport transfers, intercity trips and vehicle hire.",
    prerequisites: ["Pickup and drop points", "Date and time", "Passenger count"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the transport case", detail: "New Booking → Transport, or Bookings → Transport → New.", route: "/transport", perm: "application:create" },
      stagesStep("Transport", TRANSPORT_STAGES),
      { title: "Vehicle Assigned (3) → Driver Assigned (4)", detail: "Both are separate stages on purpose. Vehicle types and routes are master data under Transport." },
      { title: "Payment Pending (5) → Booking Confirmed (6)", detail: "Collect payment, then confirm the trip.", perm: "payment:record" },
      { title: "Pickup Ready (7) → Passenger Picked Up (8) → Trip Completed (9)", detail: "Track the trip in real time so the office can answer 'where is my car?'." },
      { title: "Delivered (10) → Closed (11)", detail: "Close once the customer confirms and the supplier cost is recorded." },
    ],
    result: "A completed trip with vehicle, driver and cost all recorded.",
    problems: [
      { problem: "No vehicle available.", fix: "See the supplier unavailable guide — offer an alternative before promising a time." },
      { problem: "The driver cannot find the passenger.", fix: "Contact details live on the case; add a note with the outcome." },
      { problem: "The trip was cancelled at the gate.", fix: "Record it and check the supplier's charge before refunding." },
    ],
    seeResult: "Bookings → Transport. Vehicles and routes are under Transport → Vehicles / Routes.",
    openTo: "/transport",
    openLabel: "Open Transport",
    related: ["create-booking", "supplier-unavailable", "supplier-cost"],
    keywords: ["transport", "vehicle", "driver", "transfer", "car", "pickup", "drop", "trip", "route"],
  },
  {
    slug: "tour-workflow",
    title: "Tour package — the 11-stage workflow",
    bn: "ট্যুর প্যাকেজ",
    category: "tour",
    what: "Packaged tours from itinerary planning through travel and post-trip feedback.",
    why: "Tours involve many travellers and several suppliers — the stages keep the itinerary, the money and the group together.",
    who: ["office_incharge", "marketing_manager", "general_manager", "super_admin"],
    when: "Group or individual package travel.",
    prerequisites: ["A destination and travel dates", "Traveller list", "A package or a costed itinerary"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the tour case", detail: "New Booking → Tour, or Bookings → Tours → New.", route: "/tours", perm: "application:create" },
      stagesStep("Tour", TOUR_STAGES),
      { title: "Itinerary Planning (3) → Quote Confirmed (4)", detail: "Build the itinerary and get the customer's acceptance of the price." },
      { title: "Payment Pending (5) → Booking Confirmed (6)", detail: "Collect the deposit or full payment per policy, then confirm with suppliers.", perm: "payment:record" },
      { title: "Pre-departure Briefing (7)", detail: "Brief the travellers — the step that prevents most on-trip problems." },
      { title: "Travel Started (8) → Travel Completed (9)", detail: "Track the trip." },
      { title: "Feedback (10) → Closed (11)", detail: "Capture feedback before closing; it feeds repeat business." },
    ],
    result: "A delivered tour with feedback captured and the case closed.",
    problems: [
      { problem: "A traveller drops out.", fix: "Adjust the traveller list and re-check supplier costs before amending the invoice." },
      { problem: "The itinerary changes after confirmation.", fix: "Record the change as a note and re-confirm the price if cost moved." },
    ],
    seeResult: "Bookings → Tours. Packages and departures are under Tours → Packages / Departures.",
    openTo: "/tours",
    openLabel: "Open Tours",
    related: ["create-booking", "create-quotation", "supplier-cost"],
    keywords: ["tour", "package", "itinerary", "group", "departure", "destination", "holiday", "trip"],
  },
  {
    slug: "hajj-workflow",
    title: "Hajj & Umrah — the 11-stage workflow",
    bn: "হজ ও ওমরাহ",
    category: "hajj",
    what: "Pilgrimage packages covering visa, ticketing, accommodation and on-ground servicing in Makkah and Madinah.",
    why: "Hajj and Umrah are regulated, seasonal and emotionally significant. The stages keep every pilgrim's paperwork and payments straight.",
    who: ["office_incharge", "visa_consultant", "general_manager", "super_admin"],
    when: "Hajj season, or Umrah year-round.",
    prerequisites: ["A valid passport with sufficient validity", "The chosen package", "Pilgrim details"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      { title: "Create the case", detail: "New Booking → Hajj or Umrah, or Bookings → Hajj → New. Hajj and Umrah are separate service types with their own identical 11-stage templates.", route: "/hajj", perm: "application:create" },
      stagesStep("Hajj / Umrah", HAJJ_STAGES),
      { title: "Package Selected (stage 3)", detail: "Packages are managed under Hajj → Packages." },
      { title: "Payment Pending (stage 4)", detail: "Pilgrim payments are usually staged — record each one against the invoice.", perm: "payment:record" },
      { title: "Visa Processing (stage 5)", detail: "The pilgrim visa. Passport handling follows the same document rules as any visa case." },
      { title: "Ticketing & Hotel (stage 6)", detail: "Flights and Makkah/Madinah accommodation are arranged together at this stage." },
      { title: "Pre-departure Orientation (7) → Departed (8)", detail: "Brief the group, then record departure." },
      { title: "On-ground Servicing (9) → Returned (10) → Closed (11)", detail: "Support in Saudi Arabia, then closure on return." },
      { title: "Groups and pilgrims", detail: "Hajj → Groups and Hajj → Pilgrims organise travellers into managed groups." },
    ],
    result: "The pilgrim completes the journey with visa, tickets and accommodation delivered, and the case closed on return.",
    problems: [
      { problem: "The passport is not valid long enough.", fix: "Renew before anything else — see the expired passport guide." },
      { problem: "Payment is being made in instalments.", fix: "Record each receipt against the same invoice; the invoice moves to partially paid until settled." },
      { problem: "A pilgrim needs to move group.", fix: "Handle it in Hajj → Groups; the case stays with the pilgrim." },
    ],
    seeResult: "Bookings → Hajj, plus Hajj → Groups and Pilgrims.",
    openTo: "/hajj",
    openLabel: "Open Hajj & Umrah",
    related: ["create-booking", "scan-passport", "record-payment", "expired-passport"],
    keywords: ["hajj", "umrah", "pilgrim", "makkah", "madinah", "package", "group", "religious"],
  },
  {
    slug: "student-workflow",
    title: "Student consultancy — the 11-stage workflow",
    bn: "স্টুডেন্ট কনসালটেন্সি",
    category: "student",
    what: "Guiding a student from counseling through university application, offer, student visa and enrolment.",
    why: "Student cases run for months across several institutions — the stages stop deadlines being missed.",
    who: ["visa_consultant", "office_incharge", "general_manager", "super_admin"],
    when: "A student wants to study abroad.",
    prerequisites: ["Academic documents", "Passport", "Target country and course"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      {
        title: "Create the student case from the Students module",
        detail: "Bookings → Students → New. The unified booking wizard does NOT create student cases — it marks Student Consultancy 'Not yet supported'. Use the Students screen.",
        route: "/students",
        perm: "application:create",
      },
      stagesStep("Student", STUDENT_STAGES),
      { title: "Counseling (3) → University Selection (4)", detail: "Advise the student, then pick target institutions. Universities are master data." },
      { title: "Application Submitted (5) → Offer Received (6)", detail: "Track each application to its decision." },
      { title: "Payment Pending (stage 7)", detail: "Consultancy and institution fees.", perm: "payment:record" },
      { title: "Visa Processing (stage 8)", detail: "The student visa follows normal visa document handling." },
      { title: "Pre-departure (9) → Enrolled (10) → Closed (11)", detail: "Brief the student, confirm enrolment, then close." },
    ],
    result: "The student is enrolled with visa and travel arranged, and the case is closed.",
    problems: [
      {
        problem: "The student service is missing from the New Booking wizard.",
        fix: "Expected. Create student cases from Bookings → Students → New instead.",
      },
      { problem: "You cannot convert a lead straight into a student case.", fix: "Lead conversion accepts only visa, air_ticket, hotel, tour, hajj and umrah. Create the customer, then start the case from Students." },
      { problem: "The offer is rejected.", fix: "Return to University Selection and apply elsewhere; keep the same case." },
    ],
    seeResult: "Bookings → Students.",
    openTo: "/students",
    openLabel: "Open Students",
    related: ["create-booking", "scan-passport", "convert-lead"],
    keywords: ["student", "university", "study abroad", "admission", "offer", "counseling", "enrol", "education"],
    availability: "partial",
    availabilityNote:
      "Student cases work fully from Bookings → Students, but they cannot be created through the unified booking wizard and cannot be reached by lead conversion or quotation in this build.",
  },
  {
    slug: "manpower-workflow",
    title: "Manpower / overseas employment — the 11-stage workflow",
    bn: "জনশক্তি / বিদেশে কর্মসংস্থান",
    category: "manpower",
    what: "Sending a worker abroad: employer verification, medical, work permit, BMET clearance, ticketing and deployment.",
    why: "Overseas recruitment is heavily regulated. BMET clearance and medical status are legal checkpoints, not optional steps.",
    who: ["office_incharge", "general_manager", "super_admin"],
    when: "A candidate is being placed with a foreign employer.",
    prerequisites: ["Candidate passport", "A verified employer and job offer", "Medical and training arrangements"],
    perms: ["application:create", "application:advance-stage"],
    steps: [
      {
        title: "Create the case from the Manpower module",
        detail: "Bookings → Manpower → New. The unified wizard does NOT create manpower cases. Internally these are recorded with the service type 'work'.",
        route: "/manpower",
        perm: "application:create",
      },
      stagesStep("Manpower (recruitment)", MANPOWER_STAGES),
      { title: "Employer Verification (stage 3)", detail: "Confirm the employer and the job offer are genuine before taking the candidate's money." },
      { title: "Medical & Training (stage 4)", detail: "Medical status is tracked on the case; a failed medical stops the process." },
      { title: "Payment Pending (stage 5)", detail: "Record what the candidate pays.", perm: "payment:record" },
      { title: "Visa / Work Permit (stage 6)", detail: "The employment visa or permit." },
      { title: "BMET Clearance (stage 7)", detail: "BMET clearance is tracked on the case and is mandatory before departure." },
      { title: "Ticketing (8) → Deployed (9)", detail: "Flights, then departure to the employer." },
      { title: "Post-deployment (10) → Closed (11)", detail: "Follow up after arrival, then close." },
    ],
    result: "The worker is deployed with medical, permit, BMET clearance and ticket all recorded.",
    problems: [
      {
        problem: "Manpower is not selectable in the New Booking wizard.",
        fix: "Expected — it is marked 'Not yet supported' there. Use Bookings → Manpower → New, which creates the case correctly.",
      },
      { problem: "The medical fails.", fix: "Stop the case at Medical & Training and add a note. Do not advance to visa." },
      { problem: "BMET clearance is delayed.", fix: "Hold at stage 7 and keep the candidate informed; do not issue a ticket first." },
    ],
    seeResult: "Bookings → Manpower.",
    openTo: "/manpower",
    openLabel: "Open Manpower",
    related: ["create-booking", "scan-passport", "convert-lead"],
    keywords: ["manpower", "work", "overseas", "bmet", "medical", "employer", "recruitment", "labour", "deployment", "job"],
    availability: "partial",
    availabilityNote:
      "Manpower cases work fully from Bookings → Manpower (stored as service type 'work'), but they cannot be created through the unified booking wizard and cannot be reached by lead conversion or quotation in this build.",
  },
];
