-- V6.x: commercial Agent onboarding profile (additive only — all nullable)

ALTER TABLE "Agent"
  ADD COLUMN "reviewedAt" TIMESTAMP(3),
  ADD COLUMN "ownerName" TEXT,
  ADD COLUMN "passportNo" TEXT,
  ADD COLUMN "dob" TIMESTAMP(3),
  ADD COLUMN "gender" TEXT,
  ADD COLUMN "nationality" TEXT,
  ADD COLUMN "businessType" TEXT,
  ADD COLUMN "businessStartDate" TIMESTAMP(3),
  ADD COLUMN "yearsExperience" INTEGER,
  ADD COLUMN "website" TEXT,
  ADD COLUMN "facebookPage" TEXT,
  ADD COLUMN "googleBusiness" TEXT,
  ADD COLUMN "officeAddress" TEXT,
  ADD COLUMN "city" TEXT,
  ADD COLUMN "district" TEXT,
  ADD COLUMN "country" TEXT,
  ADD COLUMN "postalCode" TEXT,
  ADD COLUMN "googleMapLocation" TEXT,
  ADD COLUMN "bankName" TEXT,
  ADD COLUMN "bankBranch" TEXT,
  ADD COLUMN "bankAccountName" TEXT,
  ADD COLUMN "bankAccountNumber" TEXT,
  ADD COLUMN "bankRoutingNumber" TEXT,
  ADD COLUMN "bkash" TEXT,
  ADD COLUMN "nagad" TEXT,
  ADD COLUMN "rocket" TEXT,
  ADD COLUMN "upay" TEXT,
  ADD COLUMN "openingBalanceType" TEXT,
  ADD COLUMN "openingBalance" INTEGER,
  ADD COLUMN "currency" TEXT,
  ADD COLUMN "emergencyName" TEXT,
  ADD COLUMN "emergencyRelationship" TEXT,
  ADD COLUMN "emergencyPhone" TEXT,
  ADD COLUMN "internalNotes" TEXT;
